// Auto-generated - Top 100 weapon skins
// Last updated: 2025-10-28T07:13:44.468Z

export const CS2_ITEMS_TOP100 = [
  {
    "type": "gloves",
    "weapon_category": "Gloves",
    "finish": "Spruce DDPAT",
    "wear": "Factory New",
    "wear_short": "FN",
    "rarity": "Extraordinary",
    "collection": null,
    "release_year": 2013,
    "min_float": 0.06,
    "max_float": 0.8,
    "image": "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu4vx603vRA_Olpfu-TVJ7uK9V6xsLvSEHGaA_u13ve5WSDu2jCIvtjyTg8GpIHyUOlB2CcdwQOUKs0btx4W0ZbngtgOM2I5Fn3n-iyob6y5p4ucGT-N7rQg4EtBM",
    "description": "Preferred by hand-to-hand fighters, these wraps protect the knuckles and stabilize the wrist when punching. The outer wrap is fabric screen printed with grey digital camo.\\n\\n<i>Some people say they're tough... others show it</i>",
    "id": "hand-wraps-spruce-ddpat-fn",
    "name": "Hand Wraps | Spruce DDPAT (Factory New)",
    "is_stattrak": false,
    "is_souvenir": false,
    "stattrak": false,
    "souvenir": false
  },
  {
    "type": "gloves",
    "weapon_category": "Gloves",
    "finish": "Spruce DDPAT",
    "wear": "Minimal Wear",
    "wear_short": "MW",
    "rarity": "Extraordinary",
    "collection": null,
    "release_year": 2013,
    "min_float": 0.06,
    "max_float": 0.8,
    "image": "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu4vx603vRA_Olpfu-TVJ7uK9V6xsLvSEHGaA_u13ve5WSDu2jCIvtjyTg8GpIHyUOlB2CcdwQOUKs0btx4W0ZbngtgOM2I5Fn3n-iyob6y5p4ucGT-N7rQg4EtBM",
    "description": "Preferred by hand-to-hand fighters, these wraps protect the knuckles and stabilize the wrist when punching. The outer wrap is fabric screen printed with grey digital camo.\\n\\n<i>Some people say they're tough... others show it</i>",
    "id": "hand-wraps-spruce-ddpat-mw",
    "name": "Hand Wraps | Spruce DDPAT (Minimal Wear)",
    "is_stattrak": false,
    "is_souvenir": false,
    "stattrak": false,
    "souvenir": false
  },
  {
    "type": "gloves",
    "weapon_category": "Gloves",
    "finish": "Spruce DDPAT",
    "wear": "Field-Tested",
    "wear_short": "FT",
    "rarity": "Extraordinary",
    "collection": null,
    "release_year": 2013,
    "min_float": 0.06,
    "max_float": 0.8,
    "image": "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu4vx603vRA_Olpfu-TVJ7uK9V6xsLvSEHGaA_u13ve5WSDu2jCIvtjyTg8GpIHyUOlB2CcdwQOUKs0btx4W0ZbngtgOM2I5Fn3n-iyob6y5p4ucGT-N7rQg4EtBM",
    "description": "Preferred by hand-to-hand fighters, these wraps protect the knuckles and stabilize the wrist when punching. The outer wrap is fabric screen printed with grey digital camo.\\n\\n<i>Some people say they're tough... others show it</i>",
    "id": "hand-wraps-spruce-ddpat-ft",
    "name": "Hand Wraps | Spruce DDPAT (Field-Tested)",
    "is_stattrak": false,
    "is_souvenir": false,
    "stattrak": false,
    "souvenir": false
  },
  {
    "type": "gloves",
    "weapon_category": "Gloves",
    "finish": "Spruce DDPAT",
    "wear": "Well-Worn",
    "wear_short": "WW",
    "rarity": "Extraordinary",
    "collection": null,
    "release_year": 2013,
    "min_float": 0.06,
    "max_float": 0.8,
    "image": "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu4vx603vRA_Olpfu-TVJ7uK9V6xsLvSEHGaA_u13ve5WSDu2jCIvtjyTg8GpIHyUOlB2CcdwQOUKs0btx4W0ZbngtgOM2I5Fn3n-iyob6y5p4ucGT-N7rQg4EtBM",
    "description": "Preferred by hand-to-hand fighters, these wraps protect the knuckles and stabilize the wrist when punching. The outer wrap is fabric screen printed with grey digital camo.\\n\\n<i>Some people say they're tough... others show it</i>",
    "id": "hand-wraps-spruce-ddpat-ww",
    "name": "Hand Wraps | Spruce DDPAT (Well-Worn)",
    "is_stattrak": false,
    "is_souvenir": false,
    "stattrak": false,
    "souvenir": false
  },
  {
    "type": "gloves",
    "weapon_category": "Gloves",
    "finish": "Spruce DDPAT",
    "wear": "Battle-Scarred",
    "wear_short": "BS",
    "rarity": "Extraordinary",
    "collection": null,
    "release_year": 2013,
    "min_float": 0.06,
    "max_float": 0.8,
    "image": "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu4vx603vRA_Olpfu-TVJ7uK9V6xsLvSEHGaA_u13ve5WSDu2jCIvtjyTg8GpIHyUOlB2CcdwQOUKs0btx4W0ZbngtgOM2I5Fn3n-iyob6y5p4ucGT-N7rQg4EtBM",
    "description": "Preferred by hand-to-hand fighters, these wraps protect the knuckles and stabilize the wrist when punching. The outer wrap is fabric screen printed with grey digital camo.\\n\\n<i>Some people say they're tough... others show it</i>",
    "id": "hand-wraps-spruce-ddpat-bs",
    "name": "Hand Wraps | Spruce DDPAT (Battle-Scarred)",
    "is_stattrak": false,
    "is_souvenir": false,
    "stattrak": false,
    "souvenir": false
  },
  {
    "type": "gloves",
    "weapon_category": "Gloves",
    "finish": "Desert Shamagh",
    "wear": "Factory New",
    "wear_short": "FN",
    "rarity": "Extraordinary",
    "collection": null,
    "release_year": 2013,
    "min_float": 0.06,
    "max_float": 0.8,
    "image": "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu4vx603vRA_Olpfu-TVJ7uK9V6xsLvSEHGaA_uh3svNgTBa7mggpty6RlYDtKRTILFd-XccfHbJb9FmmldPjYenqtAzXidhFnnqv2Hsb7Cpr4ulWAKYgq6HejlqSM-Bo4sNVduHnE0pUC4zeyw",
    "description": "Preferred by hand-to-hand fighters, these wraps protect the knuckles and stabilize the wrist when punching.",
    "id": "hand-wraps-desert-shamagh-fn",
    "name": "Hand Wraps | Desert Shamagh (Factory New)",
    "is_stattrak": false,
    "is_souvenir": false,
    "stattrak": false,
    "souvenir": false
  },
  {
    "type": "gloves",
    "weapon_category": "Gloves",
    "finish": "Desert Shamagh",
    "wear": "Minimal Wear",
    "wear_short": "MW",
    "rarity": "Extraordinary",
    "collection": null,
    "release_year": 2013,
    "min_float": 0.06,
    "max_float": 0.8,
    "image": "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu4vx603vRA_Olpfu-TVJ7uK9V6xsLvSEHGaA_uh3svNgTBa7mggpty6RlYDtKRTILFd-XccfHbJb9FmmldPjYenqtAzXidhFnnqv2Hsb7Cpr4ulWAKYgq6HejlqSM-Bo4sNVduHnE0pUC4zeyw",
    "description": "Preferred by hand-to-hand fighters, these wraps protect the knuckles and stabilize the wrist when punching.",
    "id": "hand-wraps-desert-shamagh-mw",
    "name": "Hand Wraps | Desert Shamagh (Minimal Wear)",
    "is_stattrak": false,
    "is_souvenir": false,
    "stattrak": false,
    "souvenir": false
  },
  {
    "type": "gloves",
    "weapon_category": "Gloves",
    "finish": "Desert Shamagh",
    "wear": "Field-Tested",
    "wear_short": "FT",
    "rarity": "Extraordinary",
    "collection": null,
    "release_year": 2013,
    "min_float": 0.06,
    "max_float": 0.8,
    "image": "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu4vx603vRA_Olpfu-TVJ7uK9V6xsLvSEHGaA_uh3svNgTBa7mggpty6RlYDtKRTILFd-XccfHbJb9FmmldPjYenqtAzXidhFnnqv2Hsb7Cpr4ulWAKYgq6HejlqSM-Bo4sNVduHnE0pUC4zeyw",
    "description": "Preferred by hand-to-hand fighters, these wraps protect the knuckles and stabilize the wrist when punching.",
    "id": "hand-wraps-desert-shamagh-ft",
    "name": "Hand Wraps | Desert Shamagh (Field-Tested)",
    "is_stattrak": false,
    "is_souvenir": false,
    "stattrak": false,
    "souvenir": false
  },
  {
    "type": "gloves",
    "weapon_category": "Gloves",
    "finish": "Desert Shamagh",
    "wear": "Well-Worn",
    "wear_short": "WW",
    "rarity": "Extraordinary",
    "collection": null,
    "release_year": 2013,
    "min_float": 0.06,
    "max_float": 0.8,
    "image": "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu4vx603vRA_Olpfu-TVJ7uK9V6xsLvSEHGaA_uh3svNgTBa7mggpty6RlYDtKRTILFd-XccfHbJb9FmmldPjYenqtAzXidhFnnqv2Hsb7Cpr4ulWAKYgq6HejlqSM-Bo4sNVduHnE0pUC4zeyw",
    "description": "Preferred by hand-to-hand fighters, these wraps protect the knuckles and stabilize the wrist when punching.",
    "id": "hand-wraps-desert-shamagh-ww",
    "name": "Hand Wraps | Desert Shamagh (Well-Worn)",
    "is_stattrak": false,
    "is_souvenir": false,
    "stattrak": false,
    "souvenir": false
  },
  {
    "type": "gloves",
    "weapon_category": "Gloves",
    "finish": "Desert Shamagh",
    "wear": "Battle-Scarred",
    "wear_short": "BS",
    "rarity": "Extraordinary",
    "collection": null,
    "release_year": 2013,
    "min_float": 0.06,
    "max_float": 0.8,
    "image": "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu4vx603vRA_Olpfu-TVJ7uK9V6xsLvSEHGaA_uh3svNgTBa7mggpty6RlYDtKRTILFd-XccfHbJb9FmmldPjYenqtAzXidhFnnqv2Hsb7Cpr4ulWAKYgq6HejlqSM-Bo4sNVduHnE0pUC4zeyw",
    "description": "Preferred by hand-to-hand fighters, these wraps protect the knuckles and stabilize the wrist when punching.",
    "id": "hand-wraps-desert-shamagh-bs",
    "name": "Hand Wraps | Desert Shamagh (Battle-Scarred)",
    "is_stattrak": false,
    "is_souvenir": false,
    "stattrak": false,
    "souvenir": false
  },
  {
    "type": "gloves",
    "weapon_category": "Gloves",
    "finish": "Badlands",
    "wear": "Factory New",
    "wear_short": "FN",
    "rarity": "Extraordinary",
    "collection": null,
    "release_year": 2013,
    "min_float": 0.06,
    "max_float": 0.8,
    "image": "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu4vx603vRA_Olpfu-TVJ7uK9V6xsLvSEHGaA_uh3svNgTBa8hxwptDi6mY70LhTPO1dmQ4xzE-NZuhexldeyZb-xtQLf2ItMzCr-i3hP5nlvse8CUKsn_aLX3g_HL_Rjto7xyDZk",
    "description": "Preferred by hand-to-hand fighters, these wraps protect the knuckles and stabilize the wrist when punching. This DIY hand protection is made of scavenged materials.\\n\\n<i>Felix turns a blind eye towards the Colation Taskforce's unsanctioned boxing league</i>",
    "id": "hand-wraps-badlands-fn",
    "name": "Hand Wraps | Badlands (Factory New)",
    "is_stattrak": false,
    "is_souvenir": false,
    "stattrak": false,
    "souvenir": false
  },
  {
    "type": "gloves",
    "weapon_category": "Gloves",
    "finish": "Badlands",
    "wear": "Minimal Wear",
    "wear_short": "MW",
    "rarity": "Extraordinary",
    "collection": null,
    "release_year": 2013,
    "min_float": 0.06,
    "max_float": 0.8,
    "image": "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu4vx603vRA_Olpfu-TVJ7uK9V6xsLvSEHGaA_uh3svNgTBa8hxwptDi6mY70LhTPO1dmQ4xzE-NZuhexldeyZb-xtQLf2ItMzCr-i3hP5nlvse8CUKsn_aLX3g_HL_Rjto7xyDZk",
    "description": "Preferred by hand-to-hand fighters, these wraps protect the knuckles and stabilize the wrist when punching. This DIY hand protection is made of scavenged materials.\\n\\n<i>Felix turns a blind eye towards the Colation Taskforce's unsanctioned boxing league</i>",
    "id": "hand-wraps-badlands-mw",
    "name": "Hand Wraps | Badlands (Minimal Wear)",
    "is_stattrak": false,
    "is_souvenir": false,
    "stattrak": false,
    "souvenir": false
  },
  {
    "type": "gloves",
    "weapon_category": "Gloves",
    "finish": "Badlands",
    "wear": "Field-Tested",
    "wear_short": "FT",
    "rarity": "Extraordinary",
    "collection": null,
    "release_year": 2013,
    "min_float": 0.06,
    "max_float": 0.8,
    "image": "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu4vx603vRA_Olpfu-TVJ7uK9V6xsLvSEHGaA_uh3svNgTBa8hxwptDi6mY70LhTPO1dmQ4xzE-NZuhexldeyZb-xtQLf2ItMzCr-i3hP5nlvse8CUKsn_aLX3g_HL_Rjto7xyDZk",
    "description": "Preferred by hand-to-hand fighters, these wraps protect the knuckles and stabilize the wrist when punching. This DIY hand protection is made of scavenged materials.\\n\\n<i>Felix turns a blind eye towards the Colation Taskforce's unsanctioned boxing league</i>",
    "id": "hand-wraps-badlands-ft",
    "name": "Hand Wraps | Badlands (Field-Tested)",
    "is_stattrak": false,
    "is_souvenir": false,
    "stattrak": false,
    "souvenir": false
  },
  {
    "type": "gloves",
    "weapon_category": "Gloves",
    "finish": "Badlands",
    "wear": "Well-Worn",
    "wear_short": "WW",
    "rarity": "Extraordinary",
    "collection": null,
    "release_year": 2013,
    "min_float": 0.06,
    "max_float": 0.8,
    "image": "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu4vx603vRA_Olpfu-TVJ7uK9V6xsLvSEHGaA_uh3svNgTBa8hxwptDi6mY70LhTPO1dmQ4xzE-NZuhexldeyZb-xtQLf2ItMzCr-i3hP5nlvse8CUKsn_aLX3g_HL_Rjto7xyDZk",
    "description": "Preferred by hand-to-hand fighters, these wraps protect the knuckles and stabilize the wrist when punching. This DIY hand protection is made of scavenged materials.\\n\\n<i>Felix turns a blind eye towards the Colation Taskforce's unsanctioned boxing league</i>",
    "id": "hand-wraps-badlands-ww",
    "name": "Hand Wraps | Badlands (Well-Worn)",
    "is_stattrak": false,
    "is_souvenir": false,
    "stattrak": false,
    "souvenir": false
  },
  {
    "type": "gloves",
    "weapon_category": "Gloves",
    "finish": "Badlands",
    "wear": "Battle-Scarred",
    "wear_short": "BS",
    "rarity": "Extraordinary",
    "collection": null,
    "release_year": 2013,
    "min_float": 0.06,
    "max_float": 0.8,
    "image": "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu4vx603vRA_Olpfu-TVJ7uK9V6xsLvSEHGaA_uh3svNgTBa8hxwptDi6mY70LhTPO1dmQ4xzE-NZuhexldeyZb-xtQLf2ItMzCr-i3hP5nlvse8CUKsn_aLX3g_HL_Rjto7xyDZk",
    "description": "Preferred by hand-to-hand fighters, these wraps protect the knuckles and stabilize the wrist when punching. This DIY hand protection is made of scavenged materials.\\n\\n<i>Felix turns a blind eye towards the Colation Taskforce's unsanctioned boxing league</i>",
    "id": "hand-wraps-badlands-bs",
    "name": "Hand Wraps | Badlands (Battle-Scarred)",
    "is_stattrak": false,
    "is_souvenir": false,
    "stattrak": false,
    "souvenir": false
  },
  {
    "type": "gloves",
    "weapon_category": "Gloves",
    "finish": "CAUTION!",
    "wear": "Factory New",
    "wear_short": "FN",
    "rarity": "Extraordinary",
    "collection": null,
    "release_year": 2013,
    "min_float": 0.06,
    "max_float": 0.8,
    "image": "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu4vx603vRA_Olpfu-TVJ7uK9V6xsLvSEHGaA_uJzsfVhSjuqqh4mpimMlYHGKS7GKE8-CsZ2TOVYtETqwdDvMLnltgGN2dlFxC33jCgcvCo64-wGBPctr6LR2xaBb-OMDXLBbA",
    "description": "Preferred by hand-to-hand fighters, these wraps protect the knuckles and stabilize the wrist when punching.",
    "id": "hand-wraps-caution!-fn",
    "name": "Hand Wraps | CAUTION! (Factory New)",
    "is_stattrak": false,
    "is_souvenir": false,
    "stattrak": false,
    "souvenir": false
  },
  {
    "type": "gloves",
    "weapon_category": "Gloves",
    "finish": "CAUTION!",
    "wear": "Minimal Wear",
    "wear_short": "MW",
    "rarity": "Extraordinary",
    "collection": null,
    "release_year": 2013,
    "min_float": 0.06,
    "max_float": 0.8,
    "image": "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu4vx603vRA_Olpfu-TVJ7uK9V6xsLvSEHGaA_uJzsfVhSjuqqh4mpimMlYHGKS7GKE8-CsZ2TOVYtETqwdDvMLnltgGN2dlFxC33jCgcvCo64-wGBPctr6LR2xaBb-OMDXLBbA",
    "description": "Preferred by hand-to-hand fighters, these wraps protect the knuckles and stabilize the wrist when punching.",
    "id": "hand-wraps-caution!-mw",
    "name": "Hand Wraps | CAUTION! (Minimal Wear)",
    "is_stattrak": false,
    "is_souvenir": false,
    "stattrak": false,
    "souvenir": false
  },
  {
    "type": "gloves",
    "weapon_category": "Gloves",
    "finish": "CAUTION!",
    "wear": "Field-Tested",
    "wear_short": "FT",
    "rarity": "Extraordinary",
    "collection": null,
    "release_year": 2013,
    "min_float": 0.06,
    "max_float": 0.8,
    "image": "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu4vx603vRA_Olpfu-TVJ7uK9V6xsLvSEHGaA_uJzsfVhSjuqqh4mpimMlYHGKS7GKE8-CsZ2TOVYtETqwdDvMLnltgGN2dlFxC33jCgcvCo64-wGBPctr6LR2xaBb-OMDXLBbA",
    "description": "Preferred by hand-to-hand fighters, these wraps protect the knuckles and stabilize the wrist when punching.",
    "id": "hand-wraps-caution!-ft",
    "name": "Hand Wraps | CAUTION! (Field-Tested)",
    "is_stattrak": false,
    "is_souvenir": false,
    "stattrak": false,
    "souvenir": false
  },
  {
    "type": "gloves",
    "weapon_category": "Gloves",
    "finish": "CAUTION!",
    "wear": "Well-Worn",
    "wear_short": "WW",
    "rarity": "Extraordinary",
    "collection": null,
    "release_year": 2013,
    "min_float": 0.06,
    "max_float": 0.8,
    "image": "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu4vx603vRA_Olpfu-TVJ7uK9V6xsLvSEHGaA_uJzsfVhSjuqqh4mpimMlYHGKS7GKE8-CsZ2TOVYtETqwdDvMLnltgGN2dlFxC33jCgcvCo64-wGBPctr6LR2xaBb-OMDXLBbA",
    "description": "Preferred by hand-to-hand fighters, these wraps protect the knuckles and stabilize the wrist when punching.",
    "id": "hand-wraps-caution!-ww",
    "name": "Hand Wraps | CAUTION! (Well-Worn)",
    "is_stattrak": false,
    "is_souvenir": false,
    "stattrak": false,
    "souvenir": false
  },
  {
    "type": "gloves",
    "weapon_category": "Gloves",
    "finish": "CAUTION!",
    "wear": "Battle-Scarred",
    "wear_short": "BS",
    "rarity": "Extraordinary",
    "collection": null,
    "release_year": 2013,
    "min_float": 0.06,
    "max_float": 0.8,
    "image": "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu4vx603vRA_Olpfu-TVJ7uK9V6xsLvSEHGaA_uJzsfVhSjuqqh4mpimMlYHGKS7GKE8-CsZ2TOVYtETqwdDvMLnltgGN2dlFxC33jCgcvCo64-wGBPctr6LR2xaBb-OMDXLBbA",
    "description": "Preferred by hand-to-hand fighters, these wraps protect the knuckles and stabilize the wrist when punching.",
    "id": "hand-wraps-caution!-bs",
    "name": "Hand Wraps | CAUTION! (Battle-Scarred)",
    "is_stattrak": false,
    "is_souvenir": false,
    "stattrak": false,
    "souvenir": false
  },
  {
    "type": "gloves",
    "weapon_category": "Gloves",
    "finish": "Duct Tape",
    "wear": "Factory New",
    "wear_short": "FN",
    "rarity": "Extraordinary",
    "collection": null,
    "release_year": 2013,
    "min_float": 0.06,
    "max_float": 0.8,
    "image": "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu4vx603vRA_Olpfu-TVJ7uK9V6xsLvSEHGaA_uJzsfVhSjuqqhkysCmRm5_8HiPCP0BpFJt3F-MM4BG9lIKxNrnj5Qze3YhGn374iStIvCtv4e8LV6An-vWDhw3fcepq_-0ZM-k",
    "description": "Preferred by hand-to-hand fighters, these wraps protect the knuckles and stabilize the wrist when punching. These scavenged hand-wraps are surprisingly durable but not especially breathable.",
    "id": "hand-wraps-duct-tape-fn",
    "name": "Hand Wraps | Duct Tape (Factory New)",
    "is_stattrak": false,
    "is_souvenir": false,
    "stattrak": false,
    "souvenir": false
  },
  {
    "type": "gloves",
    "weapon_category": "Gloves",
    "finish": "Duct Tape",
    "wear": "Minimal Wear",
    "wear_short": "MW",
    "rarity": "Extraordinary",
    "collection": null,
    "release_year": 2013,
    "min_float": 0.06,
    "max_float": 0.8,
    "image": "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu4vx603vRA_Olpfu-TVJ7uK9V6xsLvSEHGaA_uJzsfVhSjuqqhkysCmRm5_8HiPCP0BpFJt3F-MM4BG9lIKxNrnj5Qze3YhGn374iStIvCtv4e8LV6An-vWDhw3fcepq_-0ZM-k",
    "description": "Preferred by hand-to-hand fighters, these wraps protect the knuckles and stabilize the wrist when punching. These scavenged hand-wraps are surprisingly durable but not especially breathable.",
    "id": "hand-wraps-duct-tape-mw",
    "name": "Hand Wraps | Duct Tape (Minimal Wear)",
    "is_stattrak": false,
    "is_souvenir": false,
    "stattrak": false,
    "souvenir": false
  },
  {
    "type": "gloves",
    "weapon_category": "Gloves",
    "finish": "Duct Tape",
    "wear": "Field-Tested",
    "wear_short": "FT",
    "rarity": "Extraordinary",
    "collection": null,
    "release_year": 2013,
    "min_float": 0.06,
    "max_float": 0.8,
    "image": "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu4vx603vRA_Olpfu-TVJ7uK9V6xsLvSEHGaA_uJzsfVhSjuqqhkysCmRm5_8HiPCP0BpFJt3F-MM4BG9lIKxNrnj5Qze3YhGn374iStIvCtv4e8LV6An-vWDhw3fcepq_-0ZM-k",
    "description": "Preferred by hand-to-hand fighters, these wraps protect the knuckles and stabilize the wrist when punching. These scavenged hand-wraps are surprisingly durable but not especially breathable.",
    "id": "hand-wraps-duct-tape-ft",
    "name": "Hand Wraps | Duct Tape (Field-Tested)",
    "is_stattrak": false,
    "is_souvenir": false,
    "stattrak": false,
    "souvenir": false
  },
  {
    "type": "gloves",
    "weapon_category": "Gloves",
    "finish": "Duct Tape",
    "wear": "Well-Worn",
    "wear_short": "WW",
    "rarity": "Extraordinary",
    "collection": null,
    "release_year": 2013,
    "min_float": 0.06,
    "max_float": 0.8,
    "image": "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu4vx603vRA_Olpfu-TVJ7uK9V6xsLvSEHGaA_uJzsfVhSjuqqhkysCmRm5_8HiPCP0BpFJt3F-MM4BG9lIKxNrnj5Qze3YhGn374iStIvCtv4e8LV6An-vWDhw3fcepq_-0ZM-k",
    "description": "Preferred by hand-to-hand fighters, these wraps protect the knuckles and stabilize the wrist when punching. These scavenged hand-wraps are surprisingly durable but not especially breathable.",
    "id": "hand-wraps-duct-tape-ww",
    "name": "Hand Wraps | Duct Tape (Well-Worn)",
    "is_stattrak": false,
    "is_souvenir": false,
    "stattrak": false,
    "souvenir": false
  },
  {
    "type": "gloves",
    "weapon_category": "Gloves",
    "finish": "Duct Tape",
    "wear": "Battle-Scarred",
    "wear_short": "BS",
    "rarity": "Extraordinary",
    "collection": null,
    "release_year": 2013,
    "min_float": 0.06,
    "max_float": 0.8,
    "image": "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu4vx603vRA_Olpfu-TVJ7uK9V6xsLvSEHGaA_uJzsfVhSjuqqhkysCmRm5_8HiPCP0BpFJt3F-MM4BG9lIKxNrnj5Qze3YhGn374iStIvCtv4e8LV6An-vWDhw3fcepq_-0ZM-k",
    "description": "Preferred by hand-to-hand fighters, these wraps protect the knuckles and stabilize the wrist when punching. These scavenged hand-wraps are surprisingly durable but not especially breathable.",
    "id": "hand-wraps-duct-tape-bs",
    "name": "Hand Wraps | Duct Tape (Battle-Scarred)",
    "is_stattrak": false,
    "is_souvenir": false,
    "stattrak": false,
    "souvenir": false
  },
  {
    "type": "gloves",
    "weapon_category": "Gloves",
    "finish": "Cobalt Skulls",
    "wear": "Factory New",
    "wear_short": "FN",
    "rarity": "Extraordinary",
    "collection": null,
    "release_year": 2013,
    "min_float": 0.06,
    "max_float": 0.8,
    "image": "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu4vx603vRA_Olpfu-TVJ7uK9V6xsLvSEHGaA_uJzsfVhSjuqqhsmsS-MmbD7LT7CAUV7T84sBohS50H-28rkNOPl4QXc2doTyyz9hn9MuHtj4O5RVaMjrKHRhw2UY7c65sEAJ6ulU13QDytoq21v",
    "description": "Preferred by hand-to-hand fighters, these wraps protect the knuckles and stabilize the wrist when punching. These blue bias-tape handwraps are printed with skull motifs.",
    "id": "hand-wraps-cobalt-skulls-fn",
    "name": "Hand Wraps | Cobalt Skulls (Factory New)",
    "is_stattrak": false,
    "is_souvenir": false,
    "stattrak": false,
    "souvenir": false
  },
  {
    "type": "gloves",
    "weapon_category": "Gloves",
    "finish": "Cobalt Skulls",
    "wear": "Minimal Wear",
    "wear_short": "MW",
    "rarity": "Extraordinary",
    "collection": null,
    "release_year": 2013,
    "min_float": 0.06,
    "max_float": 0.8,
    "image": "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu4vx603vRA_Olpfu-TVJ7uK9V6xsLvSEHGaA_uJzsfVhSjuqqhsmsS-MmbD7LT7CAUV7T84sBohS50H-28rkNOPl4QXc2doTyyz9hn9MuHtj4O5RVaMjrKHRhw2UY7c65sEAJ6ulU13QDytoq21v",
    "description": "Preferred by hand-to-hand fighters, these wraps protect the knuckles and stabilize the wrist when punching. These blue bias-tape handwraps are printed with skull motifs.",
    "id": "hand-wraps-cobalt-skulls-mw",
    "name": "Hand Wraps | Cobalt Skulls (Minimal Wear)",
    "is_stattrak": false,
    "is_souvenir": false,
    "stattrak": false,
    "souvenir": false
  },
  {
    "type": "gloves",
    "weapon_category": "Gloves",
    "finish": "Cobalt Skulls",
    "wear": "Field-Tested",
    "wear_short": "FT",
    "rarity": "Extraordinary",
    "collection": null,
    "release_year": 2013,
    "min_float": 0.06,
    "max_float": 0.8,
    "image": "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu4vx603vRA_Olpfu-TVJ7uK9V6xsLvSEHGaA_uJzsfVhSjuqqhsmsS-MmbD7LT7CAUV7T84sBohS50H-28rkNOPl4QXc2doTyyz9hn9MuHtj4O5RVaMjrKHRhw2UY7c65sEAJ6ulU13QDytoq21v",
    "description": "Preferred by hand-to-hand fighters, these wraps protect the knuckles and stabilize the wrist when punching. These blue bias-tape handwraps are printed with skull motifs.",
    "id": "hand-wraps-cobalt-skulls-ft",
    "name": "Hand Wraps | Cobalt Skulls (Field-Tested)",
    "is_stattrak": false,
    "is_souvenir": false,
    "stattrak": false,
    "souvenir": false
  },
  {
    "type": "gloves",
    "weapon_category": "Gloves",
    "finish": "Cobalt Skulls",
    "wear": "Well-Worn",
    "wear_short": "WW",
    "rarity": "Extraordinary",
    "collection": null,
    "release_year": 2013,
    "min_float": 0.06,
    "max_float": 0.8,
    "image": "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu4vx603vRA_Olpfu-TVJ7uK9V6xsLvSEHGaA_uJzsfVhSjuqqhsmsS-MmbD7LT7CAUV7T84sBohS50H-28rkNOPl4QXc2doTyyz9hn9MuHtj4O5RVaMjrKHRhw2UY7c65sEAJ6ulU13QDytoq21v",
    "description": "Preferred by hand-to-hand fighters, these wraps protect the knuckles and stabilize the wrist when punching. These blue bias-tape handwraps are printed with skull motifs.",
    "id": "hand-wraps-cobalt-skulls-ww",
    "name": "Hand Wraps | Cobalt Skulls (Well-Worn)",
    "is_stattrak": false,
    "is_souvenir": false,
    "stattrak": false,
    "souvenir": false
  },
  {
    "type": "gloves",
    "weapon_category": "Gloves",
    "finish": "Cobalt Skulls",
    "wear": "Battle-Scarred",
    "wear_short": "BS",
    "rarity": "Extraordinary",
    "collection": null,
    "release_year": 2013,
    "min_float": 0.06,
    "max_float": 0.8,
    "image": "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu4vx603vRA_Olpfu-TVJ7uK9V6xsLvSEHGaA_uJzsfVhSjuqqhsmsS-MmbD7LT7CAUV7T84sBohS50H-28rkNOPl4QXc2doTyyz9hn9MuHtj4O5RVaMjrKHRhw2UY7c65sEAJ6ulU13QDytoq21v",
    "description": "Preferred by hand-to-hand fighters, these wraps protect the knuckles and stabilize the wrist when punching. These blue bias-tape handwraps are printed with skull motifs.",
    "id": "hand-wraps-cobalt-skulls-bs",
    "name": "Hand Wraps | Cobalt Skulls (Battle-Scarred)",
    "is_stattrak": false,
    "is_souvenir": false,
    "stattrak": false,
    "souvenir": false
  },
  {
    "type": "gloves",
    "weapon_category": "Gloves",
    "finish": "Overprint",
    "wear": "Factory New",
    "wear_short": "FN",
    "rarity": "Extraordinary",
    "collection": null,
    "release_year": 2013,
    "min_float": 0.06,
    "max_float": 0.8,
    "image": "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu4vx603vRA_Olpfu-TVJ7uK9V6xsLvSEHGaA_uJzsfVhSjuqqhsmsS-MmbD-JCTKO0JiU8EfF7tP53_gx4WhfvS3sQGM2oJGnCv8iCwd6nxq4u1RVaol_qyFhwDJN-E9tZkAdaujRUiLRlxR76SI82V2",
    "description": "Preferred by hand-to-hand fighters, these wraps protect the knuckles and stabilize the wrist when punching. These black bias-tape handwraps have been printed with rubberized geometric patterns.",
    "id": "hand-wraps-overprint-fn",
    "name": "Hand Wraps | Overprint (Factory New)",
    "is_stattrak": false,
    "is_souvenir": false,
    "stattrak": false,
    "souvenir": false
  },
  {
    "type": "gloves",
    "weapon_category": "Gloves",
    "finish": "Overprint",
    "wear": "Minimal Wear",
    "wear_short": "MW",
    "rarity": "Extraordinary",
    "collection": null,
    "release_year": 2013,
    "min_float": 0.06,
    "max_float": 0.8,
    "image": "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu4vx603vRA_Olpfu-TVJ7uK9V6xsLvSEHGaA_uJzsfVhSjuqqhsmsS-MmbD-JCTKO0JiU8EfF7tP53_gx4WhfvS3sQGM2oJGnCv8iCwd6nxq4u1RVaol_qyFhwDJN-E9tZkAdaujRUiLRlxR76SI82V2",
    "description": "Preferred by hand-to-hand fighters, these wraps protect the knuckles and stabilize the wrist when punching. These black bias-tape handwraps have been printed with rubberized geometric patterns.",
    "id": "hand-wraps-overprint-mw",
    "name": "Hand Wraps | Overprint (Minimal Wear)",
    "is_stattrak": false,
    "is_souvenir": false,
    "stattrak": false,
    "souvenir": false
  },
  {
    "type": "gloves",
    "weapon_category": "Gloves",
    "finish": "Overprint",
    "wear": "Field-Tested",
    "wear_short": "FT",
    "rarity": "Extraordinary",
    "collection": null,
    "release_year": 2013,
    "min_float": 0.06,
    "max_float": 0.8,
    "image": "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu4vx603vRA_Olpfu-TVJ7uK9V6xsLvSEHGaA_uJzsfVhSjuqqhsmsS-MmbD-JCTKO0JiU8EfF7tP53_gx4WhfvS3sQGM2oJGnCv8iCwd6nxq4u1RVaol_qyFhwDJN-E9tZkAdaujRUiLRlxR76SI82V2",
    "description": "Preferred by hand-to-hand fighters, these wraps protect the knuckles and stabilize the wrist when punching. These black bias-tape handwraps have been printed with rubberized geometric patterns.",
    "id": "hand-wraps-overprint-ft",
    "name": "Hand Wraps | Overprint (Field-Tested)",
    "is_stattrak": false,
    "is_souvenir": false,
    "stattrak": false,
    "souvenir": false
  },
  {
    "type": "gloves",
    "weapon_category": "Gloves",
    "finish": "Overprint",
    "wear": "Well-Worn",
    "wear_short": "WW",
    "rarity": "Extraordinary",
    "collection": null,
    "release_year": 2013,
    "min_float": 0.06,
    "max_float": 0.8,
    "image": "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu4vx603vRA_Olpfu-TVJ7uK9V6xsLvSEHGaA_uJzsfVhSjuqqhsmsS-MmbD-JCTKO0JiU8EfF7tP53_gx4WhfvS3sQGM2oJGnCv8iCwd6nxq4u1RVaol_qyFhwDJN-E9tZkAdaujRUiLRlxR76SI82V2",
    "description": "Preferred by hand-to-hand fighters, these wraps protect the knuckles and stabilize the wrist when punching. These black bias-tape handwraps have been printed with rubberized geometric patterns.",
    "id": "hand-wraps-overprint-ww",
    "name": "Hand Wraps | Overprint (Well-Worn)",
    "is_stattrak": false,
    "is_souvenir": false,
    "stattrak": false,
    "souvenir": false
  },
  {
    "type": "gloves",
    "weapon_category": "Gloves",
    "finish": "Overprint",
    "wear": "Battle-Scarred",
    "wear_short": "BS",
    "rarity": "Extraordinary",
    "collection": null,
    "release_year": 2013,
    "min_float": 0.06,
    "max_float": 0.8,
    "image": "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu4vx603vRA_Olpfu-TVJ7uK9V6xsLvSEHGaA_uJzsfVhSjuqqhsmsS-MmbD-JCTKO0JiU8EfF7tP53_gx4WhfvS3sQGM2oJGnCv8iCwd6nxq4u1RVaol_qyFhwDJN-E9tZkAdaujRUiLRlxR76SI82V2",
    "description": "Preferred by hand-to-hand fighters, these wraps protect the knuckles and stabilize the wrist when punching. These black bias-tape handwraps have been printed with rubberized geometric patterns.",
    "id": "hand-wraps-overprint-bs",
    "name": "Hand Wraps | Overprint (Battle-Scarred)",
    "is_stattrak": false,
    "is_souvenir": false,
    "stattrak": false,
    "souvenir": false
  },
  {
    "type": "gloves",
    "weapon_category": "Gloves",
    "finish": "Giraffe",
    "wear": "Factory New",
    "wear_short": "FN",
    "rarity": "Extraordinary",
    "collection": null,
    "release_year": 2013,
    "min_float": 0.06,
    "max_float": 0.8,
    "image": "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu4vx603vRA_Olpfu-TVJ7uK9V6xsLvSEHGaA_uJzsfVhSjuqqhsmsS-MmbD-KDnGOFB1ZcolFKFDrBG5m4e2N-OxtVTe2t1FmH3-2Csc6S044LwGA6t0rqHWjguTNLQ6spcdZKHwCm1NZ7k",
    "description": "Preferred by hand-to-hand fighters, these wraps protect the knuckles and stabilize the wrist when punching.",
    "id": "hand-wraps-giraffe-fn",
    "name": "Hand Wraps | Giraffe (Factory New)",
    "is_stattrak": false,
    "is_souvenir": false,
    "stattrak": false,
    "souvenir": false
  },
  {
    "type": "gloves",
    "weapon_category": "Gloves",
    "finish": "Giraffe",
    "wear": "Minimal Wear",
    "wear_short": "MW",
    "rarity": "Extraordinary",
    "collection": null,
    "release_year": 2013,
    "min_float": 0.06,
    "max_float": 0.8,
    "image": "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu4vx603vRA_Olpfu-TVJ7uK9V6xsLvSEHGaA_uJzsfVhSjuqqhsmsS-MmbD-KDnGOFB1ZcolFKFDrBG5m4e2N-OxtVTe2t1FmH3-2Csc6S044LwGA6t0rqHWjguTNLQ6spcdZKHwCm1NZ7k",
    "description": "Preferred by hand-to-hand fighters, these wraps protect the knuckles and stabilize the wrist when punching.",
    "id": "hand-wraps-giraffe-mw",
    "name": "Hand Wraps | Giraffe (Minimal Wear)",
    "is_stattrak": false,
    "is_souvenir": false,
    "stattrak": false,
    "souvenir": false
  },
  {
    "type": "gloves",
    "weapon_category": "Gloves",
    "finish": "Giraffe",
    "wear": "Field-Tested",
    "wear_short": "FT",
    "rarity": "Extraordinary",
    "collection": null,
    "release_year": 2013,
    "min_float": 0.06,
    "max_float": 0.8,
    "image": "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu4vx603vRA_Olpfu-TVJ7uK9V6xsLvSEHGaA_uJzsfVhSjuqqhsmsS-MmbD-KDnGOFB1ZcolFKFDrBG5m4e2N-OxtVTe2t1FmH3-2Csc6S044LwGA6t0rqHWjguTNLQ6spcdZKHwCm1NZ7k",
    "description": "Preferred by hand-to-hand fighters, these wraps protect the knuckles and stabilize the wrist when punching.",
    "id": "hand-wraps-giraffe-ft",
    "name": "Hand Wraps | Giraffe (Field-Tested)",
    "is_stattrak": false,
    "is_souvenir": false,
    "stattrak": false,
    "souvenir": false
  },
  {
    "type": "gloves",
    "weapon_category": "Gloves",
    "finish": "Giraffe",
    "wear": "Well-Worn",
    "wear_short": "WW",
    "rarity": "Extraordinary",
    "collection": null,
    "release_year": 2013,
    "min_float": 0.06,
    "max_float": 0.8,
    "image": "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu4vx603vRA_Olpfu-TVJ7uK9V6xsLvSEHGaA_uJzsfVhSjuqqhsmsS-MmbD-KDnGOFB1ZcolFKFDrBG5m4e2N-OxtVTe2t1FmH3-2Csc6S044LwGA6t0rqHWjguTNLQ6spcdZKHwCm1NZ7k",
    "description": "Preferred by hand-to-hand fighters, these wraps protect the knuckles and stabilize the wrist when punching.",
    "id": "hand-wraps-giraffe-ww",
    "name": "Hand Wraps | Giraffe (Well-Worn)",
    "is_stattrak": false,
    "is_souvenir": false,
    "stattrak": false,
    "souvenir": false
  },
  {
    "type": "gloves",
    "weapon_category": "Gloves",
    "finish": "Giraffe",
    "wear": "Battle-Scarred",
    "wear_short": "BS",
    "rarity": "Extraordinary",
    "collection": null,
    "release_year": 2013,
    "min_float": 0.06,
    "max_float": 0.8,
    "image": "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu4vx603vRA_Olpfu-TVJ7uK9V6xsLvSEHGaA_uJzsfVhSjuqqhsmsS-MmbD-KDnGOFB1ZcolFKFDrBG5m4e2N-OxtVTe2t1FmH3-2Csc6S044LwGA6t0rqHWjguTNLQ6spcdZKHwCm1NZ7k",
    "description": "Preferred by hand-to-hand fighters, these wraps protect the knuckles and stabilize the wrist when punching.",
    "id": "hand-wraps-giraffe-bs",
    "name": "Hand Wraps | Giraffe (Battle-Scarred)",
    "is_stattrak": false,
    "is_souvenir": false,
    "stattrak": false,
    "souvenir": false
  },
  {
    "type": "gloves",
    "weapon_category": "Gloves",
    "finish": "Arboreal",
    "wear": "Factory New",
    "wear_short": "FN",
    "rarity": "Extraordinary",
    "collection": null,
    "release_year": 2013,
    "min_float": 0.06,
    "max_float": 0.8,
    "image": "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu4vx603vRA_Olpfu-TVJ7uK9V6xsLvSEHGaA_uJzsfVhSjuqqhsmsS-MmbD-My7CMGlzW88vKrpf5kn9z8rhMOiz4gzWi4gQn37-inwavylu5bsHWKYm-KGG2Q7IZOE84pVVIfmnU13QD5pQMiG2",
    "description": "Preferred by hand-to-hand fighters, these wraps protect the knuckles and stabilize the wrist when punching. These bias-tape handwraps have been dyed with a forest camo pattern.",
    "id": "hand-wraps-arboreal-fn",
    "name": "Hand Wraps | Arboreal (Factory New)",
    "is_stattrak": false,
    "is_souvenir": false,
    "stattrak": false,
    "souvenir": false
  },
  {
    "type": "gloves",
    "weapon_category": "Gloves",
    "finish": "Arboreal",
    "wear": "Minimal Wear",
    "wear_short": "MW",
    "rarity": "Extraordinary",
    "collection": null,
    "release_year": 2013,
    "min_float": 0.06,
    "max_float": 0.8,
    "image": "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu4vx603vRA_Olpfu-TVJ7uK9V6xsLvSEHGaA_uJzsfVhSjuqqhsmsS-MmbD-My7CMGlzW88vKrpf5kn9z8rhMOiz4gzWi4gQn37-inwavylu5bsHWKYm-KGG2Q7IZOE84pVVIfmnU13QD5pQMiG2",
    "description": "Preferred by hand-to-hand fighters, these wraps protect the knuckles and stabilize the wrist when punching. These bias-tape handwraps have been dyed with a forest camo pattern.",
    "id": "hand-wraps-arboreal-mw",
    "name": "Hand Wraps | Arboreal (Minimal Wear)",
    "is_stattrak": false,
    "is_souvenir": false,
    "stattrak": false,
    "souvenir": false
  },
  {
    "type": "gloves",
    "weapon_category": "Gloves",
    "finish": "Arboreal",
    "wear": "Field-Tested",
    "wear_short": "FT",
    "rarity": "Extraordinary",
    "collection": null,
    "release_year": 2013,
    "min_float": 0.06,
    "max_float": 0.8,
    "image": "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu4vx603vRA_Olpfu-TVJ7uK9V6xsLvSEHGaA_uJzsfVhSjuqqhsmsS-MmbD-My7CMGlzW88vKrpf5kn9z8rhMOiz4gzWi4gQn37-inwavylu5bsHWKYm-KGG2Q7IZOE84pVVIfmnU13QD5pQMiG2",
    "description": "Preferred by hand-to-hand fighters, these wraps protect the knuckles and stabilize the wrist when punching. These bias-tape handwraps have been dyed with a forest camo pattern.",
    "id": "hand-wraps-arboreal-ft",
    "name": "Hand Wraps | Arboreal (Field-Tested)",
    "is_stattrak": false,
    "is_souvenir": false,
    "stattrak": false,
    "souvenir": false
  },
  {
    "type": "gloves",
    "weapon_category": "Gloves",
    "finish": "Arboreal",
    "wear": "Well-Worn",
    "wear_short": "WW",
    "rarity": "Extraordinary",
    "collection": null,
    "release_year": 2013,
    "min_float": 0.06,
    "max_float": 0.8,
    "image": "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu4vx603vRA_Olpfu-TVJ7uK9V6xsLvSEHGaA_uJzsfVhSjuqqhsmsS-MmbD-My7CMGlzW88vKrpf5kn9z8rhMOiz4gzWi4gQn37-inwavylu5bsHWKYm-KGG2Q7IZOE84pVVIfmnU13QD5pQMiG2",
    "description": "Preferred by hand-to-hand fighters, these wraps protect the knuckles and stabilize the wrist when punching. These bias-tape handwraps have been dyed with a forest camo pattern.",
    "id": "hand-wraps-arboreal-ww",
    "name": "Hand Wraps | Arboreal (Well-Worn)",
    "is_stattrak": false,
    "is_souvenir": false,
    "stattrak": false,
    "souvenir": false
  },
  {
    "type": "gloves",
    "weapon_category": "Gloves",
    "finish": "Arboreal",
    "wear": "Battle-Scarred",
    "wear_short": "BS",
    "rarity": "Extraordinary",
    "collection": null,
    "release_year": 2013,
    "min_float": 0.06,
    "max_float": 0.8,
    "image": "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu4vx603vRA_Olpfu-TVJ7uK9V6xsLvSEHGaA_uJzsfVhSjuqqhsmsS-MmbD-My7CMGlzW88vKrpf5kn9z8rhMOiz4gzWi4gQn37-inwavylu5bsHWKYm-KGG2Q7IZOE84pVVIfmnU13QD5pQMiG2",
    "description": "Preferred by hand-to-hand fighters, these wraps protect the knuckles and stabilize the wrist when punching. These bias-tape handwraps have been dyed with a forest camo pattern.",
    "id": "hand-wraps-arboreal-bs",
    "name": "Hand Wraps | Arboreal (Battle-Scarred)",
    "is_stattrak": false,
    "is_souvenir": false,
    "stattrak": false,
    "souvenir": false
  },
  {
    "type": "gloves",
    "weapon_category": "Gloves",
    "finish": "Leather",
    "wear": "Factory New",
    "wear_short": "FN",
    "rarity": "Extraordinary",
    "collection": null,
    "release_year": 2013,
    "min_float": 0.06,
    "max_float": 0.8,
    "image": "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu4vx603vRA_Olpfu-TVJ7uK9V6xsLvSEHGaA_uJzsfVhSjuqqhUisiuc1I2gIHmXOwAgXJF1R-NYs0G-m4fnM76wtgTWid5GmC__j35JvSpu5OscEf1yQQiiO2k",
    "description": "Preferred by hand-to-hand fighters, these wraps protect the knuckles and stabilize the wrist when punching. They are made of leather, gauze, and wicked intent.\\n\\n<i>Become notorious</i>",
    "id": "hand-wraps-leather-fn",
    "name": "Hand Wraps | Leather (Factory New)",
    "is_stattrak": false,
    "is_souvenir": false,
    "stattrak": false,
    "souvenir": false
  },
  {
    "type": "gloves",
    "weapon_category": "Gloves",
    "finish": "Leather",
    "wear": "Minimal Wear",
    "wear_short": "MW",
    "rarity": "Extraordinary",
    "collection": null,
    "release_year": 2013,
    "min_float": 0.06,
    "max_float": 0.8,
    "image": "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu4vx603vRA_Olpfu-TVJ7uK9V6xsLvSEHGaA_uJzsfVhSjuqqhUisiuc1I2gIHmXOwAgXJF1R-NYs0G-m4fnM76wtgTWid5GmC__j35JvSpu5OscEf1yQQiiO2k",
    "description": "Preferred by hand-to-hand fighters, these wraps protect the knuckles and stabilize the wrist when punching. They are made of leather, gauze, and wicked intent.\\n\\n<i>Become notorious</i>",
    "id": "hand-wraps-leather-mw",
    "name": "Hand Wraps | Leather (Minimal Wear)",
    "is_stattrak": false,
    "is_souvenir": false,
    "stattrak": false,
    "souvenir": false
  },
  {
    "type": "gloves",
    "weapon_category": "Gloves",
    "finish": "Leather",
    "wear": "Field-Tested",
    "wear_short": "FT",
    "rarity": "Extraordinary",
    "collection": null,
    "release_year": 2013,
    "min_float": 0.06,
    "max_float": 0.8,
    "image": "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu4vx603vRA_Olpfu-TVJ7uK9V6xsLvSEHGaA_uJzsfVhSjuqqhUisiuc1I2gIHmXOwAgXJF1R-NYs0G-m4fnM76wtgTWid5GmC__j35JvSpu5OscEf1yQQiiO2k",
    "description": "Preferred by hand-to-hand fighters, these wraps protect the knuckles and stabilize the wrist when punching. They are made of leather, gauze, and wicked intent.\\n\\n<i>Become notorious</i>",
    "id": "hand-wraps-leather-ft",
    "name": "Hand Wraps | Leather (Field-Tested)",
    "is_stattrak": false,
    "is_souvenir": false,
    "stattrak": false,
    "souvenir": false
  },
  {
    "type": "gloves",
    "weapon_category": "Gloves",
    "finish": "Leather",
    "wear": "Well-Worn",
    "wear_short": "WW",
    "rarity": "Extraordinary",
    "collection": null,
    "release_year": 2013,
    "min_float": 0.06,
    "max_float": 0.8,
    "image": "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu4vx603vRA_Olpfu-TVJ7uK9V6xsLvSEHGaA_uJzsfVhSjuqqhUisiuc1I2gIHmXOwAgXJF1R-NYs0G-m4fnM76wtgTWid5GmC__j35JvSpu5OscEf1yQQiiO2k",
    "description": "Preferred by hand-to-hand fighters, these wraps protect the knuckles and stabilize the wrist when punching. They are made of leather, gauze, and wicked intent.\\n\\n<i>Become notorious</i>",
    "id": "hand-wraps-leather-ww",
    "name": "Hand Wraps | Leather (Well-Worn)",
    "is_stattrak": false,
    "is_souvenir": false,
    "stattrak": false,
    "souvenir": false
  },
  {
    "type": "gloves",
    "weapon_category": "Gloves",
    "finish": "Leather",
    "wear": "Battle-Scarred",
    "wear_short": "BS",
    "rarity": "Extraordinary",
    "collection": null,
    "release_year": 2013,
    "min_float": 0.06,
    "max_float": 0.8,
    "image": "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu4vx603vRA_Olpfu-TVJ7uK9V6xsLvSEHGaA_uJzsfVhSjuqqhUisiuc1I2gIHmXOwAgXJF1R-NYs0G-m4fnM76wtgTWid5GmC__j35JvSpu5OscEf1yQQiiO2k",
    "description": "Preferred by hand-to-hand fighters, these wraps protect the knuckles and stabilize the wrist when punching. They are made of leather, gauze, and wicked intent.\\n\\n<i>Become notorious</i>",
    "id": "hand-wraps-leather-bs",
    "name": "Hand Wraps | Leather (Battle-Scarred)",
    "is_stattrak": false,
    "is_souvenir": false,
    "stattrak": false,
    "souvenir": false
  },
  {
    "type": "gloves",
    "weapon_category": "Gloves",
    "finish": "Constrictor",
    "wear": "Factory New",
    "wear_short": "FN",
    "rarity": "Extraordinary",
    "collection": null,
    "release_year": 2013,
    "min_float": 0.06,
    "max_float": 0.8,
    "image": "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu4vx603vRA_Olpfu-TVJ7uK9V6xsLvSEHGaA_uJzsfVhSjuqqg4psjaAiYTwLxTILFd-XccfHbJb9FmmltDuMrvm4wDWjoNFmyT43C0f6i1i5epUVfFwqazR3VuUNeE4sMMBcuHnE0qytnHslg",
    "description": "Preferred by hand-to-hand fighters, these wraps protect the knuckles and stabilize the wrist when punching.",
    "id": "hand-wraps-constrictor-fn",
    "name": "Hand Wraps | Constrictor (Factory New)",
    "is_stattrak": false,
    "is_souvenir": false,
    "stattrak": false,
    "souvenir": false
  },
  {
    "type": "gloves",
    "weapon_category": "Gloves",
    "finish": "Constrictor",
    "wear": "Minimal Wear",
    "wear_short": "MW",
    "rarity": "Extraordinary",
    "collection": null,
    "release_year": 2013,
    "min_float": 0.06,
    "max_float": 0.8,
    "image": "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu4vx603vRA_Olpfu-TVJ7uK9V6xsLvSEHGaA_uJzsfVhSjuqqg4psjaAiYTwLxTILFd-XccfHbJb9FmmltDuMrvm4wDWjoNFmyT43C0f6i1i5epUVfFwqazR3VuUNeE4sMMBcuHnE0qytnHslg",
    "description": "Preferred by hand-to-hand fighters, these wraps protect the knuckles and stabilize the wrist when punching.",
    "id": "hand-wraps-constrictor-mw",
    "name": "Hand Wraps | Constrictor (Minimal Wear)",
    "is_stattrak": false,
    "is_souvenir": false,
    "stattrak": false,
    "souvenir": false
  },
  {
    "type": "gloves",
    "weapon_category": "Gloves",
    "finish": "Constrictor",
    "wear": "Field-Tested",
    "wear_short": "FT",
    "rarity": "Extraordinary",
    "collection": null,
    "release_year": 2013,
    "min_float": 0.06,
    "max_float": 0.8,
    "image": "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu4vx603vRA_Olpfu-TVJ7uK9V6xsLvSEHGaA_uJzsfVhSjuqqg4psjaAiYTwLxTILFd-XccfHbJb9FmmltDuMrvm4wDWjoNFmyT43C0f6i1i5epUVfFwqazR3VuUNeE4sMMBcuHnE0qytnHslg",
    "description": "Preferred by hand-to-hand fighters, these wraps protect the knuckles and stabilize the wrist when punching.",
    "id": "hand-wraps-constrictor-ft",
    "name": "Hand Wraps | Constrictor (Field-Tested)",
    "is_stattrak": false,
    "is_souvenir": false,
    "stattrak": false,
    "souvenir": false
  },
  {
    "type": "gloves",
    "weapon_category": "Gloves",
    "finish": "Constrictor",
    "wear": "Well-Worn",
    "wear_short": "WW",
    "rarity": "Extraordinary",
    "collection": null,
    "release_year": 2013,
    "min_float": 0.06,
    "max_float": 0.8,
    "image": "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu4vx603vRA_Olpfu-TVJ7uK9V6xsLvSEHGaA_uJzsfVhSjuqqg4psjaAiYTwLxTILFd-XccfHbJb9FmmltDuMrvm4wDWjoNFmyT43C0f6i1i5epUVfFwqazR3VuUNeE4sMMBcuHnE0qytnHslg",
    "description": "Preferred by hand-to-hand fighters, these wraps protect the knuckles and stabilize the wrist when punching.",
    "id": "hand-wraps-constrictor-ww",
    "name": "Hand Wraps | Constrictor (Well-Worn)",
    "is_stattrak": false,
    "is_souvenir": false,
    "stattrak": false,
    "souvenir": false
  },
  {
    "type": "gloves",
    "weapon_category": "Gloves",
    "finish": "Constrictor",
    "wear": "Battle-Scarred",
    "wear_short": "BS",
    "rarity": "Extraordinary",
    "collection": null,
    "release_year": 2013,
    "min_float": 0.06,
    "max_float": 0.8,
    "image": "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu4vx603vRA_Olpfu-TVJ7uK9V6xsLvSEHGaA_uJzsfVhSjuqqg4psjaAiYTwLxTILFd-XccfHbJb9FmmltDuMrvm4wDWjoNFmyT43C0f6i1i5epUVfFwqazR3VuUNeE4sMMBcuHnE0qytnHslg",
    "description": "Preferred by hand-to-hand fighters, these wraps protect the knuckles and stabilize the wrist when punching.",
    "id": "hand-wraps-constrictor-bs",
    "name": "Hand Wraps | Constrictor (Battle-Scarred)",
    "is_stattrak": false,
    "is_souvenir": false,
    "stattrak": false,
    "souvenir": false
  },
  {
    "type": "gloves",
    "weapon_category": "Gloves",
    "finish": "Slaughter",
    "wear": "Factory New",
    "wear_short": "FN",
    "rarity": "Extraordinary",
    "collection": null,
    "release_year": 2013,
    "min_float": 0.06,
    "max_float": 0.8,
    "image": "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu4vx603vRA_Olpfu-TVJ7uK9V6xsLvSEHGaA_vxztN56QyimkhUzti-6kor4NzKJb1ApCMF1Q-IDuhG6l4ezMbzm7lSLj95Gmyis3yId73s5sOtXA6Ihq7qX0V98CWoovg",
    "description": "Preferred by hand-to-hand fighters, these wraps protect the knuckles and stabilize the wrist when punching. Dyed crimson, these wraps make it hard to see where the fabric ends and the bloodstains begin\\n\\n<i>Who doesn't love working with their hands?</i>",
    "id": "hand-wraps-slaughter-fn",
    "name": "Hand Wraps | Slaughter (Factory New)",
    "is_stattrak": false,
    "is_souvenir": false,
    "stattrak": false,
    "souvenir": false
  },
  {
    "type": "gloves",
    "weapon_category": "Gloves",
    "finish": "Slaughter",
    "wear": "Minimal Wear",
    "wear_short": "MW",
    "rarity": "Extraordinary",
    "collection": null,
    "release_year": 2013,
    "min_float": 0.06,
    "max_float": 0.8,
    "image": "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu4vx603vRA_Olpfu-TVJ7uK9V6xsLvSEHGaA_vxztN56QyimkhUzti-6kor4NzKJb1ApCMF1Q-IDuhG6l4ezMbzm7lSLj95Gmyis3yId73s5sOtXA6Ihq7qX0V98CWoovg",
    "description": "Preferred by hand-to-hand fighters, these wraps protect the knuckles and stabilize the wrist when punching. Dyed crimson, these wraps make it hard to see where the fabric ends and the bloodstains begin\\n\\n<i>Who doesn't love working with their hands?</i>",
    "id": "hand-wraps-slaughter-mw",
    "name": "Hand Wraps | Slaughter (Minimal Wear)",
    "is_stattrak": false,
    "is_souvenir": false,
    "stattrak": false,
    "souvenir": false
  },
  {
    "type": "gloves",
    "weapon_category": "Gloves",
    "finish": "Slaughter",
    "wear": "Field-Tested",
    "wear_short": "FT",
    "rarity": "Extraordinary",
    "collection": null,
    "release_year": 2013,
    "min_float": 0.06,
    "max_float": 0.8,
    "image": "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu4vx603vRA_Olpfu-TVJ7uK9V6xsLvSEHGaA_vxztN56QyimkhUzti-6kor4NzKJb1ApCMF1Q-IDuhG6l4ezMbzm7lSLj95Gmyis3yId73s5sOtXA6Ihq7qX0V98CWoovg",
    "description": "Preferred by hand-to-hand fighters, these wraps protect the knuckles and stabilize the wrist when punching. Dyed crimson, these wraps make it hard to see where the fabric ends and the bloodstains begin\\n\\n<i>Who doesn't love working with their hands?</i>",
    "id": "hand-wraps-slaughter-ft",
    "name": "Hand Wraps | Slaughter (Field-Tested)",
    "is_stattrak": false,
    "is_souvenir": false,
    "stattrak": false,
    "souvenir": false
  },
  {
    "type": "gloves",
    "weapon_category": "Gloves",
    "finish": "Slaughter",
    "wear": "Well-Worn",
    "wear_short": "WW",
    "rarity": "Extraordinary",
    "collection": null,
    "release_year": 2013,
    "min_float": 0.06,
    "max_float": 0.8,
    "image": "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu4vx603vRA_Olpfu-TVJ7uK9V6xsLvSEHGaA_vxztN56QyimkhUzti-6kor4NzKJb1ApCMF1Q-IDuhG6l4ezMbzm7lSLj95Gmyis3yId73s5sOtXA6Ihq7qX0V98CWoovg",
    "description": "Preferred by hand-to-hand fighters, these wraps protect the knuckles and stabilize the wrist when punching. Dyed crimson, these wraps make it hard to see where the fabric ends and the bloodstains begin\\n\\n<i>Who doesn't love working with their hands?</i>",
    "id": "hand-wraps-slaughter-ww",
    "name": "Hand Wraps | Slaughter (Well-Worn)",
    "is_stattrak": false,
    "is_souvenir": false,
    "stattrak": false,
    "souvenir": false
  },
  {
    "type": "gloves",
    "weapon_category": "Gloves",
    "finish": "Slaughter",
    "wear": "Battle-Scarred",
    "wear_short": "BS",
    "rarity": "Extraordinary",
    "collection": null,
    "release_year": 2013,
    "min_float": 0.06,
    "max_float": 0.8,
    "image": "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu4vx603vRA_Olpfu-TVJ7uK9V6xsLvSEHGaA_vxztN56QyimkhUzti-6kor4NzKJb1ApCMF1Q-IDuhG6l4ezMbzm7lSLj95Gmyis3yId73s5sOtXA6Ihq7qX0V98CWoovg",
    "description": "Preferred by hand-to-hand fighters, these wraps protect the knuckles and stabilize the wrist when punching. Dyed crimson, these wraps make it hard to see where the fabric ends and the bloodstains begin\\n\\n<i>Who doesn't love working with their hands?</i>",
    "id": "hand-wraps-slaughter-bs",
    "name": "Hand Wraps | Slaughter (Battle-Scarred)",
    "is_stattrak": false,
    "is_souvenir": false,
    "stattrak": false,
    "souvenir": false
  },
  {
    "type": "gloves",
    "weapon_category": "Gloves",
    "finish": "Eclipse",
    "wear": "Factory New",
    "wear_short": "FN",
    "rarity": "Extraordinary",
    "collection": null,
    "release_year": 2013,
    "min_float": 0.06,
    "max_float": 0.8,
    "image": "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu4r7_lb1QgTykpPf-i5U-fe9V6liNP-BDX6TzetJsuB6RiqMlxEmsDa6kor4NzKJblQlCJFxRuVetUK-kNaxNumztAXe2tkUzy_6h3sY7Chp5bwCBaRz8rqX0V8A8nSa1Q",
    "description": "These bulky hard knuckled gloves can protect the wearers hands from road rash at 60 mph. This is the original classic black design that made Tortue a household name.\\n\\n<i>Don't call it a midlife crisis</i>",
    "id": "moto-gloves-eclipse-fn",
    "name": "Moto Gloves | Eclipse (Factory New)",
    "is_stattrak": false,
    "is_souvenir": false,
    "stattrak": false,
    "souvenir": false
  },
  {
    "type": "gloves",
    "weapon_category": "Gloves",
    "finish": "Eclipse",
    "wear": "Minimal Wear",
    "wear_short": "MW",
    "rarity": "Extraordinary",
    "collection": null,
    "release_year": 2013,
    "min_float": 0.06,
    "max_float": 0.8,
    "image": "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu4r7_lb1QgTykpPf-i5U-fe9V6liNP-BDX6TzetJsuB6RiqMlxEmsDa6kor4NzKJblQlCJFxRuVetUK-kNaxNumztAXe2tkUzy_6h3sY7Chp5bwCBaRz8rqX0V8A8nSa1Q",
    "description": "These bulky hard knuckled gloves can protect the wearers hands from road rash at 60 mph. This is the original classic black design that made Tortue a household name.\\n\\n<i>Don't call it a midlife crisis</i>",
    "id": "moto-gloves-eclipse-mw",
    "name": "Moto Gloves | Eclipse (Minimal Wear)",
    "is_stattrak": false,
    "is_souvenir": false,
    "stattrak": false,
    "souvenir": false
  },
  {
    "type": "gloves",
    "weapon_category": "Gloves",
    "finish": "Eclipse",
    "wear": "Field-Tested",
    "wear_short": "FT",
    "rarity": "Extraordinary",
    "collection": null,
    "release_year": 2013,
    "min_float": 0.06,
    "max_float": 0.8,
    "image": "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu4r7_lb1QgTykpPf-i5U-fe9V6liNP-BDX6TzetJsuB6RiqMlxEmsDa6kor4NzKJblQlCJFxRuVetUK-kNaxNumztAXe2tkUzy_6h3sY7Chp5bwCBaRz8rqX0V8A8nSa1Q",
    "description": "These bulky hard knuckled gloves can protect the wearers hands from road rash at 60 mph. This is the original classic black design that made Tortue a household name.\\n\\n<i>Don't call it a midlife crisis</i>",
    "id": "moto-gloves-eclipse-ft",
    "name": "Moto Gloves | Eclipse (Field-Tested)",
    "is_stattrak": false,
    "is_souvenir": false,
    "stattrak": false,
    "souvenir": false
  },
  {
    "type": "gloves",
    "weapon_category": "Gloves",
    "finish": "Eclipse",
    "wear": "Well-Worn",
    "wear_short": "WW",
    "rarity": "Extraordinary",
    "collection": null,
    "release_year": 2013,
    "min_float": 0.06,
    "max_float": 0.8,
    "image": "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu4r7_lb1QgTykpPf-i5U-fe9V6liNP-BDX6TzetJsuB6RiqMlxEmsDa6kor4NzKJblQlCJFxRuVetUK-kNaxNumztAXe2tkUzy_6h3sY7Chp5bwCBaRz8rqX0V8A8nSa1Q",
    "description": "These bulky hard knuckled gloves can protect the wearers hands from road rash at 60 mph. This is the original classic black design that made Tortue a household name.\\n\\n<i>Don't call it a midlife crisis</i>",
    "id": "moto-gloves-eclipse-ww",
    "name": "Moto Gloves | Eclipse (Well-Worn)",
    "is_stattrak": false,
    "is_souvenir": false,
    "stattrak": false,
    "souvenir": false
  },
  {
    "type": "gloves",
    "weapon_category": "Gloves",
    "finish": "Eclipse",
    "wear": "Battle-Scarred",
    "wear_short": "BS",
    "rarity": "Extraordinary",
    "collection": null,
    "release_year": 2013,
    "min_float": 0.06,
    "max_float": 0.8,
    "image": "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu4r7_lb1QgTykpPf-i5U-fe9V6liNP-BDX6TzetJsuB6RiqMlxEmsDa6kor4NzKJblQlCJFxRuVetUK-kNaxNumztAXe2tkUzy_6h3sY7Chp5bwCBaRz8rqX0V8A8nSa1Q",
    "description": "These bulky hard knuckled gloves can protect the wearers hands from road rash at 60 mph. This is the original classic black design that made Tortue a household name.\\n\\n<i>Don't call it a midlife crisis</i>",
    "id": "moto-gloves-eclipse-bs",
    "name": "Moto Gloves | Eclipse (Battle-Scarred)",
    "is_stattrak": false,
    "is_souvenir": false,
    "stattrak": false,
    "souvenir": false
  },
  {
    "type": "gloves",
    "weapon_category": "Gloves",
    "finish": "Turtle",
    "wear": "Factory New",
    "wear_short": "FN",
    "rarity": "Extraordinary",
    "collection": null,
    "release_year": 2013,
    "min_float": 0.06,
    "max_float": 0.8,
    "image": "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu4r7_lb1QgTykpPf-i5U-fe9V6liNP-BDX6TzetJsuB6RiqMkg8itjO6lZ34LyzCAV51W9Q5W-UNsBjrk9LnMOjl4FeIi4IQxH_9iy5Kvyk_6-8FB6stq_DXhlrDNb0joc5U8W-JG5M",
    "description": "These bulky hard knuckled gloves can protect the wearers hands from road rash at 60 mph. This green and grey pair has bright orange accents.",
    "id": "moto-gloves-turtle-fn",
    "name": "Moto Gloves | Turtle (Factory New)",
    "is_stattrak": false,
    "is_souvenir": false,
    "stattrak": false,
    "souvenir": false
  },
  {
    "type": "gloves",
    "weapon_category": "Gloves",
    "finish": "Turtle",
    "wear": "Minimal Wear",
    "wear_short": "MW",
    "rarity": "Extraordinary",
    "collection": null,
    "release_year": 2013,
    "min_float": 0.06,
    "max_float": 0.8,
    "image": "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu4r7_lb1QgTykpPf-i5U-fe9V6liNP-BDX6TzetJsuB6RiqMkg8itjO6lZ34LyzCAV51W9Q5W-UNsBjrk9LnMOjl4FeIi4IQxH_9iy5Kvyk_6-8FB6stq_DXhlrDNb0joc5U8W-JG5M",
    "description": "These bulky hard knuckled gloves can protect the wearers hands from road rash at 60 mph. This green and grey pair has bright orange accents.",
    "id": "moto-gloves-turtle-mw",
    "name": "Moto Gloves | Turtle (Minimal Wear)",
    "is_stattrak": false,
    "is_souvenir": false,
    "stattrak": false,
    "souvenir": false
  },
  {
    "type": "gloves",
    "weapon_category": "Gloves",
    "finish": "Turtle",
    "wear": "Field-Tested",
    "wear_short": "FT",
    "rarity": "Extraordinary",
    "collection": null,
    "release_year": 2013,
    "min_float": 0.06,
    "max_float": 0.8,
    "image": "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu4r7_lb1QgTykpPf-i5U-fe9V6liNP-BDX6TzetJsuB6RiqMkg8itjO6lZ34LyzCAV51W9Q5W-UNsBjrk9LnMOjl4FeIi4IQxH_9iy5Kvyk_6-8FB6stq_DXhlrDNb0joc5U8W-JG5M",
    "description": "These bulky hard knuckled gloves can protect the wearers hands from road rash at 60 mph. This green and grey pair has bright orange accents.",
    "id": "moto-gloves-turtle-ft",
    "name": "Moto Gloves | Turtle (Field-Tested)",
    "is_stattrak": false,
    "is_souvenir": false,
    "stattrak": false,
    "souvenir": false
  },
  {
    "type": "gloves",
    "weapon_category": "Gloves",
    "finish": "Turtle",
    "wear": "Well-Worn",
    "wear_short": "WW",
    "rarity": "Extraordinary",
    "collection": null,
    "release_year": 2013,
    "min_float": 0.06,
    "max_float": 0.8,
    "image": "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu4r7_lb1QgTykpPf-i5U-fe9V6liNP-BDX6TzetJsuB6RiqMkg8itjO6lZ34LyzCAV51W9Q5W-UNsBjrk9LnMOjl4FeIi4IQxH_9iy5Kvyk_6-8FB6stq_DXhlrDNb0joc5U8W-JG5M",
    "description": "These bulky hard knuckled gloves can protect the wearers hands from road rash at 60 mph. This green and grey pair has bright orange accents.",
    "id": "moto-gloves-turtle-ww",
    "name": "Moto Gloves | Turtle (Well-Worn)",
    "is_stattrak": false,
    "is_souvenir": false,
    "stattrak": false,
    "souvenir": false
  },
  {
    "type": "gloves",
    "weapon_category": "Gloves",
    "finish": "Turtle",
    "wear": "Battle-Scarred",
    "wear_short": "BS",
    "rarity": "Extraordinary",
    "collection": null,
    "release_year": 2013,
    "min_float": 0.06,
    "max_float": 0.8,
    "image": "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu4r7_lb1QgTykpPf-i5U-fe9V6liNP-BDX6TzetJsuB6RiqMkg8itjO6lZ34LyzCAV51W9Q5W-UNsBjrk9LnMOjl4FeIi4IQxH_9iy5Kvyk_6-8FB6stq_DXhlrDNb0joc5U8W-JG5M",
    "description": "These bulky hard knuckled gloves can protect the wearers hands from road rash at 60 mph. This green and grey pair has bright orange accents.",
    "id": "moto-gloves-turtle-bs",
    "name": "Moto Gloves | Turtle (Battle-Scarred)",
    "is_stattrak": false,
    "is_souvenir": false,
    "stattrak": false,
    "souvenir": false
  },
  {
    "type": "gloves",
    "weapon_category": "Gloves",
    "finish": "Blood Pressure",
    "wear": "Factory New",
    "wear_short": "FN",
    "rarity": "Extraordinary",
    "collection": null,
    "release_year": 2013,
    "min_float": 0.06,
    "max_float": 0.8,
    "image": "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu4r7_lb1QgTykpPf-i5U-fe9V6liNP-BDX6TzetJs-B7TSa9kxQlti-6iIr9HiPCP0BpFMR3FuQLuhmwwdy2M--34gzXg91BzS_8iHxJuipqtrsBWaQh__LR3g7fcepqBo_CUqE",
    "description": "These bulky hard knuckled gloves can protect the wearers hands from road rash at 60 mph.",
    "id": "moto-gloves-blood-pressure-fn",
    "name": "Moto Gloves | Blood Pressure (Factory New)",
    "is_stattrak": false,
    "is_souvenir": false,
    "stattrak": false,
    "souvenir": false
  },
  {
    "type": "gloves",
    "weapon_category": "Gloves",
    "finish": "Blood Pressure",
    "wear": "Minimal Wear",
    "wear_short": "MW",
    "rarity": "Extraordinary",
    "collection": null,
    "release_year": 2013,
    "min_float": 0.06,
    "max_float": 0.8,
    "image": "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu4r7_lb1QgTykpPf-i5U-fe9V6liNP-BDX6TzetJs-B7TSa9kxQlti-6iIr9HiPCP0BpFMR3FuQLuhmwwdy2M--34gzXg91BzS_8iHxJuipqtrsBWaQh__LR3g7fcepqBo_CUqE",
    "description": "These bulky hard knuckled gloves can protect the wearers hands from road rash at 60 mph.",
    "id": "moto-gloves-blood-pressure-mw",
    "name": "Moto Gloves | Blood Pressure (Minimal Wear)",
    "is_stattrak": false,
    "is_souvenir": false,
    "stattrak": false,
    "souvenir": false
  },
  {
    "type": "gloves",
    "weapon_category": "Gloves",
    "finish": "Blood Pressure",
    "wear": "Field-Tested",
    "wear_short": "FT",
    "rarity": "Extraordinary",
    "collection": null,
    "release_year": 2013,
    "min_float": 0.06,
    "max_float": 0.8,
    "image": "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu4r7_lb1QgTykpPf-i5U-fe9V6liNP-BDX6TzetJs-B7TSa9kxQlti-6iIr9HiPCP0BpFMR3FuQLuhmwwdy2M--34gzXg91BzS_8iHxJuipqtrsBWaQh__LR3g7fcepqBo_CUqE",
    "description": "These bulky hard knuckled gloves can protect the wearers hands from road rash at 60 mph.",
    "id": "moto-gloves-blood-pressure-ft",
    "name": "Moto Gloves | Blood Pressure (Field-Tested)",
    "is_stattrak": false,
    "is_souvenir": false,
    "stattrak": false,
    "souvenir": false
  },
  {
    "type": "gloves",
    "weapon_category": "Gloves",
    "finish": "Blood Pressure",
    "wear": "Well-Worn",
    "wear_short": "WW",
    "rarity": "Extraordinary",
    "collection": null,
    "release_year": 2013,
    "min_float": 0.06,
    "max_float": 0.8,
    "image": "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu4r7_lb1QgTykpPf-i5U-fe9V6liNP-BDX6TzetJs-B7TSa9kxQlti-6iIr9HiPCP0BpFMR3FuQLuhmwwdy2M--34gzXg91BzS_8iHxJuipqtrsBWaQh__LR3g7fcepqBo_CUqE",
    "description": "These bulky hard knuckled gloves can protect the wearers hands from road rash at 60 mph.",
    "id": "moto-gloves-blood-pressure-ww",
    "name": "Moto Gloves | Blood Pressure (Well-Worn)",
    "is_stattrak": false,
    "is_souvenir": false,
    "stattrak": false,
    "souvenir": false
  },
  {
    "type": "gloves",
    "weapon_category": "Gloves",
    "finish": "Blood Pressure",
    "wear": "Battle-Scarred",
    "wear_short": "BS",
    "rarity": "Extraordinary",
    "collection": null,
    "release_year": 2013,
    "min_float": 0.06,
    "max_float": 0.8,
    "image": "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu4r7_lb1QgTykpPf-i5U-fe9V6liNP-BDX6TzetJs-B7TSa9kxQlti-6iIr9HiPCP0BpFMR3FuQLuhmwwdy2M--34gzXg91BzS_8iHxJuipqtrsBWaQh__LR3g7fcepqBo_CUqE",
    "description": "These bulky hard knuckled gloves can protect the wearers hands from road rash at 60 mph.",
    "id": "moto-gloves-blood-pressure-bs",
    "name": "Moto Gloves | Blood Pressure (Battle-Scarred)",
    "is_stattrak": false,
    "is_souvenir": false,
    "stattrak": false,
    "souvenir": false
  },
  {
    "type": "gloves",
    "weapon_category": "Gloves",
    "finish": "Finish Line",
    "wear": "Factory New",
    "wear_short": "FN",
    "rarity": "Extraordinary",
    "collection": null,
    "release_year": 2013,
    "min_float": 0.06,
    "max_float": 0.8,
    "image": "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu4r7_lb1QgTykpPf-i5U-fe9V6liNP-BDX6TzetJs-lsTCK2hyIhvzyCpY31NC74OUR1X8wfHbJb9Fmmm4WyZeKx5QLdg91DzS6vjHgauCk_teoLVaYjrqPWjA7JZbw64JdSJuHnE0oPZti6RQ",
    "description": "These bulky hard knuckled gloves can protect the wearers hands from road rash at 60 mph.",
    "id": "moto-gloves-finish-line-fn",
    "name": "Moto Gloves | Finish Line (Factory New)",
    "is_stattrak": false,
    "is_souvenir": false,
    "stattrak": false,
    "souvenir": false
  },
  {
    "type": "gloves",
    "weapon_category": "Gloves",
    "finish": "Finish Line",
    "wear": "Minimal Wear",
    "wear_short": "MW",
    "rarity": "Extraordinary",
    "collection": null,
    "release_year": 2013,
    "min_float": 0.06,
    "max_float": 0.8,
    "image": "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu4r7_lb1QgTykpPf-i5U-fe9V6liNP-BDX6TzetJs-lsTCK2hyIhvzyCpY31NC74OUR1X8wfHbJb9Fmmm4WyZeKx5QLdg91DzS6vjHgauCk_teoLVaYjrqPWjA7JZbw64JdSJuHnE0oPZti6RQ",
    "description": "These bulky hard knuckled gloves can protect the wearers hands from road rash at 60 mph.",
    "id": "moto-gloves-finish-line-mw",
    "name": "Moto Gloves | Finish Line (Minimal Wear)",
    "is_stattrak": false,
    "is_souvenir": false,
    "stattrak": false,
    "souvenir": false
  },
  {
    "type": "gloves",
    "weapon_category": "Gloves",
    "finish": "Finish Line",
    "wear": "Field-Tested",
    "wear_short": "FT",
    "rarity": "Extraordinary",
    "collection": null,
    "release_year": 2013,
    "min_float": 0.06,
    "max_float": 0.8,
    "image": "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu4r7_lb1QgTykpPf-i5U-fe9V6liNP-BDX6TzetJs-lsTCK2hyIhvzyCpY31NC74OUR1X8wfHbJb9Fmmm4WyZeKx5QLdg91DzS6vjHgauCk_teoLVaYjrqPWjA7JZbw64JdSJuHnE0oPZti6RQ",
    "description": "These bulky hard knuckled gloves can protect the wearers hands from road rash at 60 mph.",
    "id": "moto-gloves-finish-line-ft",
    "name": "Moto Gloves | Finish Line (Field-Tested)",
    "is_stattrak": false,
    "is_souvenir": false,
    "stattrak": false,
    "souvenir": false
  },
  {
    "type": "gloves",
    "weapon_category": "Gloves",
    "finish": "Finish Line",
    "wear": "Well-Worn",
    "wear_short": "WW",
    "rarity": "Extraordinary",
    "collection": null,
    "release_year": 2013,
    "min_float": 0.06,
    "max_float": 0.8,
    "image": "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu4r7_lb1QgTykpPf-i5U-fe9V6liNP-BDX6TzetJs-lsTCK2hyIhvzyCpY31NC74OUR1X8wfHbJb9Fmmm4WyZeKx5QLdg91DzS6vjHgauCk_teoLVaYjrqPWjA7JZbw64JdSJuHnE0oPZti6RQ",
    "description": "These bulky hard knuckled gloves can protect the wearers hands from road rash at 60 mph.",
    "id": "moto-gloves-finish-line-ww",
    "name": "Moto Gloves | Finish Line (Well-Worn)",
    "is_stattrak": false,
    "is_souvenir": false,
    "stattrak": false,
    "souvenir": false
  },
  {
    "type": "gloves",
    "weapon_category": "Gloves",
    "finish": "Finish Line",
    "wear": "Battle-Scarred",
    "wear_short": "BS",
    "rarity": "Extraordinary",
    "collection": null,
    "release_year": 2013,
    "min_float": 0.06,
    "max_float": 0.8,
    "image": "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu4r7_lb1QgTykpPf-i5U-fe9V6liNP-BDX6TzetJs-lsTCK2hyIhvzyCpY31NC74OUR1X8wfHbJb9Fmmm4WyZeKx5QLdg91DzS6vjHgauCk_teoLVaYjrqPWjA7JZbw64JdSJuHnE0oPZti6RQ",
    "description": "These bulky hard knuckled gloves can protect the wearers hands from road rash at 60 mph.",
    "id": "moto-gloves-finish-line-bs",
    "name": "Moto Gloves | Finish Line (Battle-Scarred)",
    "is_stattrak": false,
    "is_souvenir": false,
    "stattrak": false,
    "souvenir": false
  },
  {
    "type": "gloves",
    "weapon_category": "Gloves",
    "finish": "POW!",
    "wear": "Factory New",
    "wear_short": "FN",
    "rarity": "Extraordinary",
    "collection": null,
    "release_year": 2013,
    "min_float": 0.06,
    "max_float": 0.8,
    "image": "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu4r7_lb1QgTykpPf-i5U-fe9V6liNP-BDX6TzetJs-lmTCaMlxIovgKNn47vOGWXPw4gWJJ3RucMtELqxtyyN7jmswTYjN9Gziutjn9O6X1v4ekEBfB35OSJ2GagYo_N",
    "description": "These bulky hard knuckled gloves can protect the wearers hands from road rash at 60 mph. This pair has been covered in brightly colored comic book onomatopoeia.",
    "id": "moto-gloves-pow!-fn",
    "name": "Moto Gloves | POW! (Factory New)",
    "is_stattrak": false,
    "is_souvenir": false,
    "stattrak": false,
    "souvenir": false
  },
  {
    "type": "gloves",
    "weapon_category": "Gloves",
    "finish": "POW!",
    "wear": "Minimal Wear",
    "wear_short": "MW",
    "rarity": "Extraordinary",
    "collection": null,
    "release_year": 2013,
    "min_float": 0.06,
    "max_float": 0.8,
    "image": "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu4r7_lb1QgTykpPf-i5U-fe9V6liNP-BDX6TzetJs-lmTCaMlxIovgKNn47vOGWXPw4gWJJ3RucMtELqxtyyN7jmswTYjN9Gziutjn9O6X1v4ekEBfB35OSJ2GagYo_N",
    "description": "These bulky hard knuckled gloves can protect the wearers hands from road rash at 60 mph. This pair has been covered in brightly colored comic book onomatopoeia.",
    "id": "moto-gloves-pow!-mw",
    "name": "Moto Gloves | POW! (Minimal Wear)",
    "is_stattrak": false,
    "is_souvenir": false,
    "stattrak": false,
    "souvenir": false
  },
  {
    "type": "gloves",
    "weapon_category": "Gloves",
    "finish": "POW!",
    "wear": "Field-Tested",
    "wear_short": "FT",
    "rarity": "Extraordinary",
    "collection": null,
    "release_year": 2013,
    "min_float": 0.06,
    "max_float": 0.8,
    "image": "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu4r7_lb1QgTykpPf-i5U-fe9V6liNP-BDX6TzetJs-lmTCaMlxIovgKNn47vOGWXPw4gWJJ3RucMtELqxtyyN7jmswTYjN9Gziutjn9O6X1v4ekEBfB35OSJ2GagYo_N",
    "description": "These bulky hard knuckled gloves can protect the wearers hands from road rash at 60 mph. This pair has been covered in brightly colored comic book onomatopoeia.",
    "id": "moto-gloves-pow!-ft",
    "name": "Moto Gloves | POW! (Field-Tested)",
    "is_stattrak": false,
    "is_souvenir": false,
    "stattrak": false,
    "souvenir": false
  },
  {
    "type": "gloves",
    "weapon_category": "Gloves",
    "finish": "POW!",
    "wear": "Well-Worn",
    "wear_short": "WW",
    "rarity": "Extraordinary",
    "collection": null,
    "release_year": 2013,
    "min_float": 0.06,
    "max_float": 0.8,
    "image": "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu4r7_lb1QgTykpPf-i5U-fe9V6liNP-BDX6TzetJs-lmTCaMlxIovgKNn47vOGWXPw4gWJJ3RucMtELqxtyyN7jmswTYjN9Gziutjn9O6X1v4ekEBfB35OSJ2GagYo_N",
    "description": "These bulky hard knuckled gloves can protect the wearers hands from road rash at 60 mph. This pair has been covered in brightly colored comic book onomatopoeia.",
    "id": "moto-gloves-pow!-ww",
    "name": "Moto Gloves | POW! (Well-Worn)",
    "is_stattrak": false,
    "is_souvenir": false,
    "stattrak": false,
    "souvenir": false
  },
  {
    "type": "gloves",
    "weapon_category": "Gloves",
    "finish": "POW!",
    "wear": "Battle-Scarred",
    "wear_short": "BS",
    "rarity": "Extraordinary",
    "collection": null,
    "release_year": 2013,
    "min_float": 0.06,
    "max_float": 0.8,
    "image": "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu4r7_lb1QgTykpPf-i5U-fe9V6liNP-BDX6TzetJs-lmTCaMlxIovgKNn47vOGWXPw4gWJJ3RucMtELqxtyyN7jmswTYjN9Gziutjn9O6X1v4ekEBfB35OSJ2GagYo_N",
    "description": "These bulky hard knuckled gloves can protect the wearers hands from road rash at 60 mph. This pair has been covered in brightly colored comic book onomatopoeia.",
    "id": "moto-gloves-pow!-bs",
    "name": "Moto Gloves | POW! (Battle-Scarred)",
    "is_stattrak": false,
    "is_souvenir": false,
    "stattrak": false,
    "souvenir": false
  },
  {
    "type": "gloves",
    "weapon_category": "Gloves",
    "finish": "3rd Commando Company",
    "wear": "Factory New",
    "wear_short": "FN",
    "rarity": "Extraordinary",
    "collection": null,
    "release_year": 2013,
    "min_float": 0.06,
    "max_float": 0.8,
    "image": "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu4r7_lb1QgTykpPf-i5U-fe9V6liNP-BDX6TzetJs-5kQii9kRIYuC6OpYf8ID3ecAYjD5pyF7MOtBKxxIezMO604waLjYpBySX9iS8avSY64u4EUaZwq6LJz1aW_2ihBdg",
    "description": "These bulky hard knuckled gloves can protect the wearers hands from road rash at 60 mph.",
    "id": "moto-gloves-3rd-commando-company-fn",
    "name": "Moto Gloves | 3rd Commando Company (Factory New)",
    "is_stattrak": false,
    "is_souvenir": false,
    "stattrak": false,
    "souvenir": false
  },
  {
    "type": "gloves",
    "weapon_category": "Gloves",
    "finish": "3rd Commando Company",
    "wear": "Minimal Wear",
    "wear_short": "MW",
    "rarity": "Extraordinary",
    "collection": null,
    "release_year": 2013,
    "min_float": 0.06,
    "max_float": 0.8,
    "image": "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu4r7_lb1QgTykpPf-i5U-fe9V6liNP-BDX6TzetJs-5kQii9kRIYuC6OpYf8ID3ecAYjD5pyF7MOtBKxxIezMO604waLjYpBySX9iS8avSY64u4EUaZwq6LJz1aW_2ihBdg",
    "description": "These bulky hard knuckled gloves can protect the wearers hands from road rash at 60 mph.",
    "id": "moto-gloves-3rd-commando-company-mw",
    "name": "Moto Gloves | 3rd Commando Company (Minimal Wear)",
    "is_stattrak": false,
    "is_souvenir": false,
    "stattrak": false,
    "souvenir": false
  },
  {
    "type": "gloves",
    "weapon_category": "Gloves",
    "finish": "3rd Commando Company",
    "wear": "Field-Tested",
    "wear_short": "FT",
    "rarity": "Extraordinary",
    "collection": null,
    "release_year": 2013,
    "min_float": 0.06,
    "max_float": 0.8,
    "image": "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu4r7_lb1QgTykpPf-i5U-fe9V6liNP-BDX6TzetJs-5kQii9kRIYuC6OpYf8ID3ecAYjD5pyF7MOtBKxxIezMO604waLjYpBySX9iS8avSY64u4EUaZwq6LJz1aW_2ihBdg",
    "description": "These bulky hard knuckled gloves can protect the wearers hands from road rash at 60 mph.",
    "id": "moto-gloves-3rd-commando-company-ft",
    "name": "Moto Gloves | 3rd Commando Company (Field-Tested)",
    "is_stattrak": false,
    "is_souvenir": false,
    "stattrak": false,
    "souvenir": false
  },
  {
    "type": "gloves",
    "weapon_category": "Gloves",
    "finish": "3rd Commando Company",
    "wear": "Well-Worn",
    "wear_short": "WW",
    "rarity": "Extraordinary",
    "collection": null,
    "release_year": 2013,
    "min_float": 0.06,
    "max_float": 0.8,
    "image": "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu4r7_lb1QgTykpPf-i5U-fe9V6liNP-BDX6TzetJs-5kQii9kRIYuC6OpYf8ID3ecAYjD5pyF7MOtBKxxIezMO604waLjYpBySX9iS8avSY64u4EUaZwq6LJz1aW_2ihBdg",
    "description": "These bulky hard knuckled gloves can protect the wearers hands from road rash at 60 mph.",
    "id": "moto-gloves-3rd-commando-company-ww",
    "name": "Moto Gloves | 3rd Commando Company (Well-Worn)",
    "is_stattrak": false,
    "is_souvenir": false,
    "stattrak": false,
    "souvenir": false
  },
  {
    "type": "gloves",
    "weapon_category": "Gloves",
    "finish": "3rd Commando Company",
    "wear": "Battle-Scarred",
    "wear_short": "BS",
    "rarity": "Extraordinary",
    "collection": null,
    "release_year": 2013,
    "min_float": 0.06,
    "max_float": 0.8,
    "image": "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu4r7_lb1QgTykpPf-i5U-fe9V6liNP-BDX6TzetJs-5kQii9kRIYuC6OpYf8ID3ecAYjD5pyF7MOtBKxxIezMO604waLjYpBySX9iS8avSY64u4EUaZwq6LJz1aW_2ihBdg",
    "description": "These bulky hard knuckled gloves can protect the wearers hands from road rash at 60 mph.",
    "id": "moto-gloves-3rd-commando-company-bs",
    "name": "Moto Gloves | 3rd Commando Company (Battle-Scarred)",
    "is_stattrak": false,
    "is_souvenir": false,
    "stattrak": false,
    "souvenir": false
  },
  {
    "type": "gloves",
    "weapon_category": "Gloves",
    "finish": "Spearmint",
    "wear": "Factory New",
    "wear_short": "FN",
    "rarity": "Extraordinary",
    "collection": null,
    "release_year": 2013,
    "min_float": 0.06,
    "max_float": 0.8,
    "image": "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu4r7_lb1QgTykpPf-i5U-fe9V6liNP-BDX6TzetJvehnWxanhxQmvTqJn7DxJCrRJxhzWZZ2ROJcsUa5ltexZbjgsgSLi98UzCX9jigf6Htv470GAqEm_aPWkUifZsrSdwA0",
    "description": "These bulky hard knuckled gloves can protect the wearers hands from road rash at 60 mph. White leather and red stitching make these gloves as stylish as they are comfortable.\\n\\n<i>For what he's charging us, you'd think Huxley could at least throw in a tin of mints... - Felix Riley, Commanding Officer</i>",
    "id": "moto-gloves-spearmint-fn",
    "name": "Moto Gloves | Spearmint (Factory New)",
    "is_stattrak": false,
    "is_souvenir": false,
    "stattrak": false,
    "souvenir": false
  },
  {
    "type": "gloves",
    "weapon_category": "Gloves",
    "finish": "Spearmint",
    "wear": "Minimal Wear",
    "wear_short": "MW",
    "rarity": "Extraordinary",
    "collection": null,
    "release_year": 2013,
    "min_float": 0.06,
    "max_float": 0.8,
    "image": "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu4r7_lb1QgTykpPf-i5U-fe9V6liNP-BDX6TzetJvehnWxanhxQmvTqJn7DxJCrRJxhzWZZ2ROJcsUa5ltexZbjgsgSLi98UzCX9jigf6Htv470GAqEm_aPWkUifZsrSdwA0",
    "description": "These bulky hard knuckled gloves can protect the wearers hands from road rash at 60 mph. White leather and red stitching make these gloves as stylish as they are comfortable.\\n\\n<i>For what he's charging us, you'd think Huxley could at least throw in a tin of mints... - Felix Riley, Commanding Officer</i>",
    "id": "moto-gloves-spearmint-mw",
    "name": "Moto Gloves | Spearmint (Minimal Wear)",
    "is_stattrak": false,
    "is_souvenir": false,
    "stattrak": false,
    "souvenir": false
  },
  {
    "type": "gloves",
    "weapon_category": "Gloves",
    "finish": "Spearmint",
    "wear": "Field-Tested",
    "wear_short": "FT",
    "rarity": "Extraordinary",
    "collection": null,
    "release_year": 2013,
    "min_float": 0.06,
    "max_float": 0.8,
    "image": "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu4r7_lb1QgTykpPf-i5U-fe9V6liNP-BDX6TzetJvehnWxanhxQmvTqJn7DxJCrRJxhzWZZ2ROJcsUa5ltexZbjgsgSLi98UzCX9jigf6Htv470GAqEm_aPWkUifZsrSdwA0",
    "description": "These bulky hard knuckled gloves can protect the wearers hands from road rash at 60 mph. White leather and red stitching make these gloves as stylish as they are comfortable.\\n\\n<i>For what he's charging us, you'd think Huxley could at least throw in a tin of mints... - Felix Riley, Commanding Officer</i>",
    "id": "moto-gloves-spearmint-ft",
    "name": "Moto Gloves | Spearmint (Field-Tested)",
    "is_stattrak": false,
    "is_souvenir": false,
    "stattrak": false,
    "souvenir": false
  },
  {
    "type": "gloves",
    "weapon_category": "Gloves",
    "finish": "Spearmint",
    "wear": "Well-Worn",
    "wear_short": "WW",
    "rarity": "Extraordinary",
    "collection": null,
    "release_year": 2013,
    "min_float": 0.06,
    "max_float": 0.8,
    "image": "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu4r7_lb1QgTykpPf-i5U-fe9V6liNP-BDX6TzetJvehnWxanhxQmvTqJn7DxJCrRJxhzWZZ2ROJcsUa5ltexZbjgsgSLi98UzCX9jigf6Htv470GAqEm_aPWkUifZsrSdwA0",
    "description": "These bulky hard knuckled gloves can protect the wearers hands from road rash at 60 mph. White leather and red stitching make these gloves as stylish as they are comfortable.\\n\\n<i>For what he's charging us, you'd think Huxley could at least throw in a tin of mints... - Felix Riley, Commanding Officer</i>",
    "id": "moto-gloves-spearmint-ww",
    "name": "Moto Gloves | Spearmint (Well-Worn)",
    "is_stattrak": false,
    "is_souvenir": false,
    "stattrak": false,
    "souvenir": false
  },
  {
    "type": "gloves",
    "weapon_category": "Gloves",
    "finish": "Spearmint",
    "wear": "Battle-Scarred",
    "wear_short": "BS",
    "rarity": "Extraordinary",
    "collection": null,
    "release_year": 2013,
    "min_float": 0.06,
    "max_float": 0.8,
    "image": "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu4r7_lb1QgTykpPf-i5U-fe9V6liNP-BDX6TzetJvehnWxanhxQmvTqJn7DxJCrRJxhzWZZ2ROJcsUa5ltexZbjgsgSLi98UzCX9jigf6Htv470GAqEm_aPWkUifZsrSdwA0",
    "description": "These bulky hard knuckled gloves can protect the wearers hands from road rash at 60 mph. White leather and red stitching make these gloves as stylish as they are comfortable.\\n\\n<i>For what he's charging us, you'd think Huxley could at least throw in a tin of mints... - Felix Riley, Commanding Officer</i>",
    "id": "moto-gloves-spearmint-bs",
    "name": "Moto Gloves | Spearmint (Battle-Scarred)",
    "is_stattrak": false,
    "is_souvenir": false,
    "stattrak": false,
    "souvenir": false
  },
  {
    "type": "gloves",
    "weapon_category": "Gloves",
    "finish": "Boom!",
    "wear": "Factory New",
    "wear_short": "FN",
    "rarity": "Extraordinary",
    "collection": null,
    "release_year": 2013,
    "min_float": 0.06,
    "max_float": 0.8,
    "image": "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu4r7_lb1QgTykpPf-i5U-fe9V6liNP-BDX6TzetJve5nQBaxmhIqjDGMnYftby-RbFUoX8d0QOJbsBfpltLgYryz41ffjowWmCj_3C4cvH4-6-ZUVqc7uvqAYlGEDh0",
    "description": "These bulky hard knuckled gloves can protect the wearers hands from road rash at 60 mph. This pair has been covered in comic book onomatopoeia.\\n\\n<i>POW! BOOM! BIFF!</i>",
    "id": "moto-gloves-boom!-fn",
    "name": "Moto Gloves | Boom! (Factory New)",
    "is_stattrak": false,
    "is_souvenir": false,
    "stattrak": false,
    "souvenir": false
  },
  {
    "type": "gloves",
    "weapon_category": "Gloves",
    "finish": "Boom!",
    "wear": "Minimal Wear",
    "wear_short": "MW",
    "rarity": "Extraordinary",
    "collection": null,
    "release_year": 2013,
    "min_float": 0.06,
    "max_float": 0.8,
    "image": "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu4r7_lb1QgTykpPf-i5U-fe9V6liNP-BDX6TzetJve5nQBaxmhIqjDGMnYftby-RbFUoX8d0QOJbsBfpltLgYryz41ffjowWmCj_3C4cvH4-6-ZUVqc7uvqAYlGEDh0",
    "description": "These bulky hard knuckled gloves can protect the wearers hands from road rash at 60 mph. This pair has been covered in comic book onomatopoeia.\\n\\n<i>POW! BOOM! BIFF!</i>",
    "id": "moto-gloves-boom!-mw",
    "name": "Moto Gloves | Boom! (Minimal Wear)",
    "is_stattrak": false,
    "is_souvenir": false,
    "stattrak": false,
    "souvenir": false
  },
  {
    "type": "gloves",
    "weapon_category": "Gloves",
    "finish": "Boom!",
    "wear": "Field-Tested",
    "wear_short": "FT",
    "rarity": "Extraordinary",
    "collection": null,
    "release_year": 2013,
    "min_float": 0.06,
    "max_float": 0.8,
    "image": "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu4r7_lb1QgTykpPf-i5U-fe9V6liNP-BDX6TzetJve5nQBaxmhIqjDGMnYftby-RbFUoX8d0QOJbsBfpltLgYryz41ffjowWmCj_3C4cvH4-6-ZUVqc7uvqAYlGEDh0",
    "description": "These bulky hard knuckled gloves can protect the wearers hands from road rash at 60 mph. This pair has been covered in comic book onomatopoeia.\\n\\n<i>POW! BOOM! BIFF!</i>",
    "id": "moto-gloves-boom!-ft",
    "name": "Moto Gloves | Boom! (Field-Tested)",
    "is_stattrak": false,
    "is_souvenir": false,
    "stattrak": false,
    "souvenir": false
  },
  {
    "type": "gloves",
    "weapon_category": "Gloves",
    "finish": "Boom!",
    "wear": "Well-Worn",
    "wear_short": "WW",
    "rarity": "Extraordinary",
    "collection": null,
    "release_year": 2013,
    "min_float": 0.06,
    "max_float": 0.8,
    "image": "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu4r7_lb1QgTykpPf-i5U-fe9V6liNP-BDX6TzetJve5nQBaxmhIqjDGMnYftby-RbFUoX8d0QOJbsBfpltLgYryz41ffjowWmCj_3C4cvH4-6-ZUVqc7uvqAYlGEDh0",
    "description": "These bulky hard knuckled gloves can protect the wearers hands from road rash at 60 mph. This pair has been covered in comic book onomatopoeia.\\n\\n<i>POW! BOOM! BIFF!</i>",
    "id": "moto-gloves-boom!-ww",
    "name": "Moto Gloves | Boom! (Well-Worn)",
    "is_stattrak": false,
    "is_souvenir": false,
    "stattrak": false,
    "souvenir": false
  },
  {
    "type": "gloves",
    "weapon_category": "Gloves",
    "finish": "Boom!",
    "wear": "Battle-Scarred",
    "wear_short": "BS",
    "rarity": "Extraordinary",
    "collection": null,
    "release_year": 2013,
    "min_float": 0.06,
    "max_float": 0.8,
    "image": "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu4r7_lb1QgTykpPf-i5U-fe9V6liNP-BDX6TzetJve5nQBaxmhIqjDGMnYftby-RbFUoX8d0QOJbsBfpltLgYryz41ffjowWmCj_3C4cvH4-6-ZUVqc7uvqAYlGEDh0",
    "description": "These bulky hard knuckled gloves can protect the wearers hands from road rash at 60 mph. This pair has been covered in comic book onomatopoeia.\\n\\n<i>POW! BOOM! BIFF!</i>",
    "id": "moto-gloves-boom!-bs",
    "name": "Moto Gloves | Boom! (Battle-Scarred)",
    "is_stattrak": false,
    "is_souvenir": false,
    "stattrak": false,
    "souvenir": false
  }
]
