import type { PublicLoadout } from "./types"

export const mockLoadouts: PublicLoadout[] = [
  {
    id: "1",
    name: "Budget Beast",
    slug: "budget-beast",
    budget: 100,
    totalCost: 87.5,
    items: [
      {
        slot: "rifle",
        item: {
          id: "ak47-redline",
          name: "AK-47 | Redline",
          imageUrl: "/ak-47-redline-cs2-skin.jpg",
          rarity: "classified",
          price: 32.5,
        },
        price: 32.5,
      },
      {
        slot: "pistol",
        item: {
          id: "glock-water-elemental",
          name: "Glock-18 | Water Elemental",
          imageUrl: "/glock-water-elemental-cs2.jpg",
          rarity: "restricted",
          price: 18.0,
        },
        price: 18.0,
      },
      {
        slot: "knife",
        item: {
          id: "bayonet-safari",
          name: "Bayonet | Safari Mesh",
          imageUrl: "/bayonet-safari-mesh-cs2.jpg",
          rarity: "covert",
          price: 27.0,
        },
        price: 27.0,
      },
      {
        slot: "gloves",
        item: {
          id: "gloves-emerald",
          name: "Hand Wraps | Emerald",
          imageUrl: "/hand-wraps-emerald-cs2.jpg",
          rarity: "restricted",
          price: 10.0,
        },
        price: 10.0,
      },
    ],
    upvotes: 142,
    views: 1250,
    isUpvotedByUser: false,
    author: {
      id: "user1",
      username: "ProPlayer123",
    },
    createdAt: "2025-01-10T12:00:00Z",
  },
  {
    id: "2",
    name: "Blue Fade Collection",
    slug: "blue-fade-collection",
    budget: 500,
    totalCost: 478.25,
    items: [
      {
        slot: "rifle",
        item: {
          id: "m4a4-poseidon",
          name: "M4A4 | Poseidon",
          imageUrl: "/m4a4-poseidon-cs2-blue.jpg",
          rarity: "classified",
          price: 125.0,
        },
        price: 125.0,
      },
      {
        slot: "pistol",
        item: {
          id: "deagle-blaze",
          name: "Desert Eagle | Blaze",
          imageUrl: "/desert-eagle-blaze-cs2.jpg",
          rarity: "restricted",
          price: 89.5,
        },
        price: 89.5,
      },
      {
        slot: "knife",
        item: {
          id: "karambit-fade",
          name: "Karambit | Fade",
          imageUrl: "/karambit-fade-cs2.jpg",
          rarity: "covert",
          price: 215.0,
        },
        price: 215.0,
      },
      {
        slot: "gloves",
        item: {
          id: "gloves-cobalt",
          name: "Sport Gloves | Cobalt Skulls",
          imageUrl: "/sport-gloves-cobalt-cs2.jpg",
          rarity: "covert",
          price: 48.75,
        },
        price: 48.75,
      },
    ],
    upvotes: 289,
    views: 3420,
    isUpvotedByUser: true,
    author: {
      id: "user2",
      username: "SkinCollector",
    },
    createdAt: "2025-01-09T15:30:00Z",
  },
  {
    id: "3",
    name: "Starter Pack",
    slug: "starter-pack",
    budget: 50,
    totalCost: 45.0,
    items: [
      {
        slot: "rifle",
        item: {
          id: "ak47-elite-build",
          name: "AK-47 | Elite Build",
          imageUrl: "/ak-47-elite-build-cs2.jpg",
          rarity: "milspec",
          price: 15.0,
        },
        price: 15.0,
      },
      {
        slot: "pistol",
        item: {
          id: "usp-kill-confirmed",
          name: "USP-S | Kill Confirmed",
          imageUrl: "/usp-kill-confirmed-cs2.jpg",
          rarity: "classified",
          price: 22.0,
        },
        price: 22.0,
      },
      {
        slot: "knife",
        item: {
          id: "navaja-safari",
          name: "Navaja Knife | Safari Mesh",
          imageUrl: "/navaja-knife-cs2.jpg",
          rarity: "covert",
          price: 8.0,
        },
        price: 8.0,
      },
    ],
    upvotes: 87,
    views: 890,
    isUpvotedByUser: false,
    author: {
      id: "user3",
      username: "NewbieGamer",
    },
    createdAt: "2025-01-11T08:15:00Z",
  },
  {
    id: "4",
    name: "Fire & Ice Premium",
    slug: "fire-ice-premium",
    budget: 1000,
    totalCost: 945.5,
    items: [
      {
        slot: "rifle",
        item: {
          id: "awp-dragon-lore",
          name: "AWP | Dragon Lore",
          imageUrl: "/awp-dragon-lore-cs2.jpg",
          rarity: "contraband",
          price: 425.0,
        },
        price: 425.0,
      },
      {
        slot: "pistol",
        item: {
          id: "deagle-printstream",
          name: "Desert Eagle | Printstream",
          imageUrl: "/desert-eagle-printstream-cs2.jpg",
          rarity: "classified",
          price: 95.5,
        },
        price: 95.5,
      },
      {
        slot: "knife",
        item: {
          id: "butterfly-marble-fade",
          name: "Butterfly Knife | Marble Fade",
          imageUrl: "/butterfly-knife-marble-fade-cs2.jpg",
          rarity: "covert",
          price: 325.0,
        },
        price: 325.0,
      },
      {
        slot: "gloves",
        item: {
          id: "gloves-vice",
          name: "Sport Gloves | Vice",
          imageUrl: "/sport-gloves-vice-cs2.jpg",
          rarity: "covert",
          price: 100.0,
        },
        price: 100.0,
      },
    ],
    upvotes: 512,
    views: 5820,
    isUpvotedByUser: false,
    author: {
      id: "user4",
      username: "EliteTrader",
    },
    createdAt: "2025-01-08T19:45:00Z",
  },
  {
    id: "5",
    name: "Mid-Tier Meta",
    slug: "mid-tier-meta",
    budget: 200,
    totalCost: 195.75,
    items: [
      {
        slot: "rifle",
        item: {
          id: "m4a1s-hyper-beast",
          name: "M4A1-S | Hyper Beast",
          imageUrl: "/m4a1-s-hyper-beast-cs2.jpg",
          rarity: "covert",
          price: 65.0,
        },
        price: 65.0,
      },
      {
        slot: "pistol",
        item: {
          id: "glock-fade",
          name: "Glock-18 | Fade",
          imageUrl: "/glock-fade-cs2.jpg",
          rarity: "restricted",
          price: 42.5,
        },
        price: 42.5,
      },
      {
        slot: "knife",
        item: {
          id: "flip-doppler",
          name: "Flip Knife | Doppler",
          imageUrl: "/placeholder.svg?height=100&width=200",
          rarity: "covert",
          price: 58.25,
        },
        price: 58.25,
      },
      {
        slot: "gloves",
        item: {
          id: "gloves-forest",
          name: "Driver Gloves | Forest DDPAT",
          imageUrl: "/placeholder.svg?height=100&width=200",
          rarity: "restricted",
          price: 30.0,
        },
        price: 30.0,
      },
    ],
    upvotes: 203,
    views: 2150,
    isUpvotedByUser: true,
    author: {
      id: "user5",
      username: "CS2Veteran",
    },
    createdAt: "2025-01-07T14:20:00Z",
  },
  {
    id: "6",
    name: "Classic Military",
    slug: "classic-military",
    budget: 150,
    totalCost: 142.0,
    items: [
      {
        slot: "rifle",
        item: {
          id: "ak47-vulcan",
          name: "AK-47 | Vulcan",
          imageUrl: "/placeholder.svg?height=100&width=200",
          rarity: "covert",
          price: 55.0,
        },
        price: 55.0,
      },
      {
        slot: "pistol",
        item: {
          id: "usp-orion",
          name: "USP-S | Orion",
          imageUrl: "/placeholder.svg?height=100&width=200",
          rarity: "classified",
          price: 28.0,
        },
        price: 28.0,
      },
      {
        slot: "knife",
        item: {
          id: "huntsman-night",
          name: "Huntsman Knife | Night",
          imageUrl: "/placeholder.svg?height=100&width=200",
          rarity: "covert",
          price: 45.0,
        },
        price: 45.0,
      },
      {
        slot: "gloves",
        item: {
          id: "gloves-bronze",
          name: "Specialist Gloves | Bronze Morph",
          imageUrl: "/placeholder.svg?height=100&width=200",
          rarity: "restricted",
          price: 14.0,
        },
        price: 14.0,
      },
    ],
    upvotes: 156,
    views: 1680,
    isUpvotedByUser: false,
    author: {
      id: "user6",
      username: "TacticalGamer",
    },
    createdAt: "2025-01-06T10:30:00Z",
  },
]
