import type { Item, SearchResult, WatchlistItem, Alert, PortfolioEntry } from "./types"

export const mockItems: Item[] = [
  {
    id: "ak-47-case-hardened",
    name: "AK-47 | Case Hardened",
    type: "weapon_skin",
    weapon: "AK-47",
    finish: "Case Hardened",
    paint_index: 44,
    rarity: "Classified",
    collection: "The Arms Deal Collection",
    case: "CS:GO Weapon Case",
    release_year: 2013,
    float_min: 0.0,
    float_max: 1.0,
    color_hue: 210,
    known_rare_patterns: [661, 670, 321, 168],
    images: {
      thumb: "/ak-47-case-hardened-blue-gem.jpg",
      hero: "/ak-47-case-hardened-detailed-view.jpg",
    },
    markets: [
      { name: "Steam", currency: "USD", price: 425.0, fee_incl: true, last_seen: "2025-10-08T16:10:00Z" },
      { name: "Buff", currency: "USD", price: 398.2, fee_incl: true, last_seen: "2025-10-08T16:09:00Z" },
      { name: "DMarket", currency: "USD", price: 405.7, fee_incl: true, last_seen: "2025-10-08T16:08:30Z" },
      { name: "Skinport", currency: "USD", price: 412.5, fee_incl: true, last_seen: "2025-10-08T16:07:00Z" },
      { name: "CSFloat", currency: "USD", price: 419.0, fee_incl: true, last_seen: "2025-10-08T16:06:00Z" },
    ],
    popularity: 0.82,
  },
  {
    id: "m4a4-howl",
    name: "M4A4 | Howl",
    type: "weapon_skin",
    weapon: "M4A4",
    finish: "Howl",
    paint_index: 309,
    rarity: "Contraband",
    collection: "The Huntsman Collection",
    case: "Huntsman Weapon Case",
    release_year: 2014,
    float_min: 0.0,
    float_max: 0.7,
    color_hue: 25,
    images: {
      thumb: "/m4a4-howl-contraband.jpg",
      hero: "/m4a4-howl-detailed-view.jpg",
    },
    markets: [
      { name: "Steam", currency: "USD", price: 4850.0, fee_incl: true, last_seen: "2025-10-08T16:10:00Z" },
      { name: "Buff", currency: "USD", price: 4620.0, fee_incl: true, last_seen: "2025-10-08T16:09:00Z" },
      { name: "DMarket", currency: "USD", price: 4725.0, fee_incl: true, last_seen: "2025-10-08T16:08:30Z" },
      { name: "Skinport", currency: "USD", price: 4780.0, fee_incl: true, last_seen: "2025-10-08T16:07:00Z" },
    ],
    popularity: 0.95,
  },
  {
    id: "awp-dragon-lore",
    name: "AWP | Dragon Lore",
    type: "weapon_skin",
    weapon: "AWP",
    finish: "Dragon Lore",
    paint_index: 344,
    rarity: "Covert",
    collection: "The Cobblestone Collection",
    case: "Cobblestone Souvenir Package",
    release_year: 2014,
    float_min: 0.0,
    float_max: 0.7,
    color_hue: 45,
    images: {
      thumb: "/awp-dragon-lore.jpg",
      hero: "/awp-dragon-lore-detailed-view.jpg",
    },
    markets: [
      { name: "Steam", currency: "USD", price: 8200.0, fee_incl: true, last_seen: "2025-10-08T16:10:00Z" },
      { name: "Buff", currency: "USD", price: 7850.0, fee_incl: true, last_seen: "2025-10-08T16:09:00Z" },
      { name: "DMarket", currency: "USD", price: 8050.0, fee_incl: true, last_seen: "2025-10-08T16:08:30Z" },
      { name: "Skinport", currency: "USD", price: 8150.0, fee_incl: true, last_seen: "2025-10-08T16:07:00Z" },
    ],
    popularity: 0.98,
  },
  {
    id: "karambit-fade",
    name: "Karambit | Fade",
    type: "weapon_skin",
    weapon: "Karambit",
    finish: "Fade",
    paint_index: 38,
    rarity: "Covert",
    collection: "The Arms Deal Collection",
    case: "CS:GO Weapon Case",
    release_year: 2013,
    float_min: 0.0,
    float_max: 0.08,
    color_hue: 320,
    images: {
      thumb: "/karambit-fade-knife.jpg",
      hero: "/karambit-fade-knife.jpg",
    },
    markets: [
      { name: "Steam", currency: "USD", price: 1850.0, fee_incl: true, last_seen: "2025-10-08T16:10:00Z" },
      { name: "Buff", currency: "USD", price: 1780.0, fee_incl: true, last_seen: "2025-10-08T16:09:00Z" },
      { name: "DMarket", currency: "USD", price: 1820.0, fee_incl: true, last_seen: "2025-10-08T16:08:30Z" },
    ],
    popularity: 0.88,
  },
  {
    id: "glock-fade",
    name: "Glock-18 | Fade",
    type: "weapon_skin",
    weapon: "Glock-18",
    finish: "Fade",
    paint_index: 38,
    rarity: "Restricted",
    collection: "The Arms Deal Collection",
    case: "CS:GO Weapon Case",
    release_year: 2013,
    float_min: 0.0,
    float_max: 0.08,
    color_hue: 300,
    images: {
      thumb: "/glock-18-fade.jpg",
      hero: "/glock-18-fade.jpg",
    },
    markets: [
      { name: "Steam", currency: "USD", price: 425.0, fee_incl: true, last_seen: "2025-10-08T16:10:00Z" },
      { name: "Buff", currency: "USD", price: 410.0, fee_incl: true, last_seen: "2025-10-08T16:09:00Z" },
      { name: "Skinport", currency: "USD", price: 418.0, fee_incl: true, last_seen: "2025-10-08T16:07:00Z" },
    ],
    popularity: 0.75,
  },
]

export const mockSearchResults: SearchResult[] = [
  {
    id: "sticker-holo-vox-katana",
    name: "Sticker | Vox (Holo) | Katowice 2014",
    type: "sticker",
    rarity: "Extraordinary",
    release_year: 2014,
    holo: true,
    images: { thumb: "/vox-katowice-2014-holo-sticker.jpg" },
    best_price: { market: "Skinport", currency: "USD", price: 9300.0 },
    delta_7d: "+2.1%",
    delta_30d: "+6.7%",
  },
  {
    id: "karambit-fade",
    name: "Karambit | Fade",
    type: "weapon_skin",
    rarity: "Covert",
    release_year: 2013,
    images: { thumb: "/karambit-fade-knife.jpg" },
    best_price: { market: "Buff", currency: "USD", price: 1850.0 },
    delta_7d: "+1.2%",
    delta_30d: "+3.4%",
    lowest_float: 0.0001,
  },
  {
    id: "glock-fade",
    name: "Glock-18 | Fade",
    type: "weapon_skin",
    rarity: "Restricted",
    release_year: 2013,
    images: { thumb: "/glock-18-fade.jpg" },
    best_price: { market: "Steam", currency: "USD", price: 425.0 },
    delta_7d: "-0.5%",
    delta_30d: "+1.8%",
    lowest_float: 0.0003,
  },
  {
    id: "ak-47-case-hardened",
    name: "AK-47 | Case Hardened",
    type: "weapon_skin",
    rarity: "Classified",
    release_year: 2013,
    images: { thumb: "/ak-47-case-hardened-blue-gem.jpg" },
    best_price: { market: "Buff", currency: "USD", price: 398.2 },
    delta_7d: "+2.3%",
    delta_30d: "+5.1%",
    lowest_float: 0.0002,
  },
  {
    id: "m4a4-howl",
    name: "M4A4 | Howl",
    type: "weapon_skin",
    rarity: "Contraband",
    release_year: 2014,
    images: { thumb: "/m4a4-howl-contraband.jpg" },
    best_price: { market: "Buff", currency: "USD", price: 4620.0 },
    delta_7d: "+1.5%",
    delta_30d: "+4.2%",
    lowest_float: 0.0001,
  },
  {
    id: "awp-dragon-lore",
    name: "AWP | Dragon Lore",
    type: "weapon_skin",
    rarity: "Covert",
    release_year: 2014,
    images: { thumb: "/awp-dragon-lore.jpg" },
    best_price: { market: "Buff", currency: "USD", price: 7850.0 },
    delta_7d: "+0.8%",
    delta_30d: "+2.9%",
    lowest_float: 0.0001,
  },
]

export const mockWatchlist: WatchlistItem[] = [
  {
    id: "1",
    item_id: "ak-47-case-hardened",
    item_name: "AK-47 | Case Hardened",
    item_image: "/ak-47-case-hardened.jpg",
    added_date: "2025-09-15",
    current_price: 425.0,
    price_change_7d: "+2.3%",
    alerts_enabled: true,
  },
  {
    id: "2",
    item_id: "m4a4-howl",
    item_name: "M4A4 | Howl",
    item_image: "/m4a4-howl.jpg",
    added_date: "2025-09-20",
    current_price: 4850.0,
    price_change_7d: "+1.5%",
    alerts_enabled: true,
  },
  {
    id: "3",
    item_id: "awp-dragon-lore",
    item_name: "AWP | Dragon Lore",
    item_image: "/awp-dragon-lore.jpg",
    added_date: "2025-09-25",
    current_price: 8200.0,
    price_change_7d: "+0.8%",
    alerts_enabled: false,
  },
]

export const mockAlerts: Alert[] = [
  {
    id: "1",
    item_id: "ak-47-case-hardened",
    item_name: "AK-47 | Case Hardened",
    trigger_type: "price_below",
    trigger_value: "400",
    market: "Buff",
    channels: ["email", "web_push"],
    enabled: true,
    created_date: "2025-09-15",
  },
  {
    id: "2",
    item_id: "awp-dragon-lore",
    item_name: "AWP | Dragon Lore",
    trigger_type: "float_below",
    trigger_value: "0.01",
    channels: ["discord"],
    enabled: true,
    created_date: "2025-09-18",
  },
  {
    id: "3",
    item_id: "m4a4-howl",
    item_name: "M4A4 | Howl",
    trigger_type: "price_drop",
    trigger_value: "5",
    channels: ["email"],
    enabled: false,
    created_date: "2025-09-22",
  },
]

export const mockPortfolio: PortfolioEntry[] = [
  {
    id: "1",
    item_id: "ak-47-case-hardened",
    item_name: "AK-47 | Case Hardened",
    item_image: "/ak-47-case-hardened.jpg",
    quantity: 1,
    buy_price: 380.0,
    buy_date: "2025-08-10",
    marketplace: "Buff",
    current_price: 425.0,
  },
  {
    id: "2",
    item_id: "glock-fade",
    item_name: "Glock-18 | Fade",
    item_image: "/glock-18-fade.jpg",
    quantity: 2,
    buy_price: 410.0,
    buy_date: "2025-09-01",
    marketplace: "Steam",
    current_price: 425.0,
  },
  {
    id: "3",
    item_id: "karambit-fade",
    item_name: "Karambit | Fade",
    item_image: "/karambit-fade-knife.jpg",
    quantity: 1,
    buy_price: 1750.0,
    buy_date: "2025-07-15",
    marketplace: "Buff",
    current_price: 1850.0,
  },
]
